### ISSUE TITLE
List widget flickers on some Android Chrome browsers

### ISSUE THREAD

**Issue by apetresc** [Shopify/dashing#109]
A picture is worth a thousand words, so this 8-second video should be worth, by my calculations, about 192,000 words:

[![ScreenShot](https://f.cloud.github.com/assets/14872/414958/04ead272-ac27-11e2-8946-329b7f179c99.png)](http://www.youtube.com/watch?v=i0raT1GgtIA)

Basically, I have a simple dashboard with a 2-second scheduled job that updates each widget (including that big list widget on the right). On all my desktop browsers, this works flawlessly, but on the Android browser on my GoogleTV (shown in the video) you can very clearly see the list widget flickering every two seconds as it updates. It's pretty annoying.

I realize this is probably just poor Javascript performance on the browser's end, but I was wondering if there's any known workarounds in Dashing? It hurts the appeal of a big TV-sized dashboard to have it constantly flicker.

Thanks!

**Comment by kivancsahici** [comment]
In case anybody is still interested, I wrote a small gist for updating the values inline

https://gist.github.com/kivancsahici/371b0de9752fafa9f4939926c971acf3
