### ISSUE TITLE
Changing the URL to access dashboard

### ISSUE THREAD

**Issue by MartynKeigher** [Shopify/dashing#111]
Hey all, 

I have a lab server at http://lab.martynkeigher.com 

On this Ubuntu 12.04 server I have both Apache installed (using port 80) and dashing (using port 3030). 

I copied the 'sampletv' dashboard and create a new erb file called dashing.erb and it is viewable at: http://lab.martynkeigher.com:3030/dashing

So, in an effort to remove the ':3030' from the URL, I have added the following to the Apache/sites-available/default file: http://pastebin.com/AfkiTmVi

If you need to see the full contents of the default file then please go here: http://pastebin.com/k4WViFur 

So now, if you go to http://lab.martynkeigher.com/dashing it works, kinda...but not fully!

Can you please go to the above URL and let me know why and what I need to change?

Thank you so much! :)

Martyn.

**Comment by bean5** [comment]
There is a great wiki page on using dashing on parked domains. The page is at https://github.com/Shopify/dashing/wiki/How-To:-Run-dashing-on-a-sub-path

**Comment by odrino14** [comment]
hi @bean5 i tried this but it is not working for me
i got a return 404

**Comment by odrino14** [comment]
@MartynKeigher did u solve ur problem?
