### ISSUE TITLE
fresh setup, sample only has the "try this: curl...." line displayed

### ISSUE THREAD

**Issue by Fuzzwah** [Shopify/dashing#117]
Up front, I'm a total Ruby newb so I'm expecting this is something I've got misconfigured.

I've downloaded and installed the 1.9.3 RubyInstaller (from rubyinstaller.org) onto my Win8 machine. I also downloaded and installed the 1.9.3 devkit from ri.org too (since the output of very first command in the "getting started" guide explained I needed this).

I then walk through the getting started steps. At the "bundle" step I was told that I didn't have bundle, so I guessed and did a "gem install bundle" and after that completed was able to complete the bundle step.

After I start dashing I go to http://localhost:3030/sample and all I see is a grey page with:

```
Try this: curl -d '{ "auth_token": "YOUR_AUTH_TOKEN", "text": "Hey, Look what I can do!" }' \http://localhost:3030/widgets/welcome
```

Since I don't have curl on here I attempted to use a push.rb based on the example. I gem install'd httparty and created a push.rb that looks like this:

```
require 'httparty'
require 'json'

HTTParty.post('http://localhost:3030/widgets/welcome',
  :body => { auth_token: "YOUR_AUTH_TOKEN", text: "Hey, Look what I can do!" }.to_json)
```

I then ran this with out an error message like thus: ruby push.rb

I refresh the http://localhost:3030/sample page but still only see a grey page with:

```
Try this: curl -d '{ "auth_token": "YOUR_AUTH_TOKEN", "text": "Hey, Look what I can do!" }' \http://localhost:3030/widgets/welcome
```

What am I doing wrong?

**Comment by RajaCD** [comment]
@jrgns  No luck even after installing node.js windows installer.

Im using windows 7 Enterprise.

**Comment by RajaCD** [comment]
@sikosis  Maxthon Cloud Browser didn't work for me.

**Comment by R2Developer** [comment]
Facing same problem, not working in chrome and firefox, just seeing blank (dark) page..

**Comment by RobotChicken** [comment]
Had the same issue, then installed Node.js as recommended here. I installed in the dashboard project directory and it started working. Thanks for the ideas.
