### ISSUE TITLE
Error installing dashing

### ISSUE THREAD

**Issue by Abbie2020** [Shopify/dashing#125]
Hi, I'm a total noob and got this error while trying to install dashing. What does it mean and what should I do? Thanks

ERROR:  Error installing dashing:
    ERROR: Failed to build gem native extension.

```
    /usr/bin/ruby1.9.1 extconf.rb
```

/usr/local/lib/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/local/lib/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from extconf.rb:2:in `<main>'

**Comment by quedayone** [comment]
You need to have the Command line tools installed on the Mac.
Try:
xcode-select --install
Then:
gem install dashing

**Comment by berry2012** [comment]
I have same issue on Amazon linux
