### ISSUE TITLE
play html5 audio on value change

### ISSUE THREAD

**Issue by kayaj** [Shopify/dashing#146]
hey guys!
first off: awesome dashboard you've made here.
i'm using it and i am very happy with it.

now, i'd like to have a little icing on the cake: how to achieve a html5 audio trigger if a value of a specific job changes?

best regards

**Comment by markymark292** [comment]
@kayaj Did you ever implement sound? I am having the same issue you did...How do you do it? 

Any help or Sample ruby code and matching coffee script would be greatly received. 

Thanks in advance,.
