### ISSUE TITLE
dashing stopped working (after update?)

### ISSUE THREAD

**Issue by Sgoettschkes** [Shopify/dashing#177]
I am running dashing locally in a Ubuntu vm and remote on heroku. Everything worked fine until today where I tried to add redis object storing (using the instructions here: https://gocardless.com/blog/raspberry-pi-metric-dashboards/).

At first I thought I had introduced a bug, but rolling back to a previous version doesn't help. All I get is this error message for every job:

```
scheduler caught exception:
undefined method `[]=' for false:FalseClass
/var/lib/gems/1.9.1/gems/dashing-1.2.0/lib/dashing.rb:127:in `send_event'
/vagrant/jobs/facebook.rb:20:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.23/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.23/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.23/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.23/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.23/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
```

It works on heroku, even after I commited the new Gemlock file and deploying it. I'm not a ruby developer so I'm a bit stuck here. Any help is appreciated! Thanks.

**Comment by marcin-at-taulia** [comment]
Thanks @maakuth ! You saved my day.

**Comment by jrboden1** [comment]
Just ran into this issue as well. However, deleting the history.yml file isn't correcting it for me. I find it weird how after changing nothing but the .erb files, I get this message. The error is really frustrating.

**Comment by nadarashwin** [comment]
Worked for me as well, but strange thing is my history.yml was complete blank but the moment i got it deleted everything started working fine

**Comment by poalcospe** [comment]
Worked for me as well thanks :+1:

**Comment by evignaux** [comment]
Many thanks, it worked for me too ;)
