### ISSUE TITLE
Possible to fix the x- & y-axis of the graph-widget

### ISSUE THREAD

**Issue by LKLG** [Shopify/dashing#186]
Hi,

Is it possible to fix the scale of x-y-axis, so that only the data changes of the graph-widget?
In my case i need a graph-widget, that is 500 units (max input is 500) high and 22 units wide (7.oo to 18.oo in 30min steps). 
So i hope anyone could understand my Request.

My english is not the best

Greets from Germany,
LKLG

**Comment by hasanoa** [comment]
Hi,

If I have 3 different graphs with different max values. How can I assign differrent yMax values? 

Sorry about my English,

Regards,
hasanoa

**Comment by hasanoa** [comment]
Hi again,

I created different y-scaled graphs with creating different graph-widgets: graph (max:1600), graph2 (max:12000), graph3 (max 5000000000).

Meters' min-max values are assigned with data-min, data-max values in erb file. But graphs' are not, are they?
