### ISSUE TITLE
How to load history.yml into highcharts graph?

### ISSUE THREAD

**Issue by mikechau** [Shopify/dashing#204]
Hi,

I have a horizontal highcharts bar chart:

`horizonbarstack.coffee:`
<pre>
class Dashing.Horizonbarstack extends Dashing.Widget

  ready: ->
    Highcharts.getOptions().colors = Highcharts.map(Highcharts.getOptions().colors, (color) ->
      Highcharts.Color(color).setOpacity(0.82).get "rgba"
    )

  createChart: (series, categories, color) ->
    container = $(@node).find('.horizon-container')
    if $(container)[0]
      @chart = new Highcharts.Chart(

        chart:
          renderTo: $(container)[0]
          type: "bar"
          backgroundColor: null
          marginTop: 0
          marginRight: 15

        title:
          text: ''

        legend:
          enabled: false
          reversed: true
          borderColor: 'white'
          borderWidth: 2

        xAxis:
          categories: categories
          labels:
            enabled: false
          minorGridLineWidth: 0
          minorTickLength: 0
          tickLength: 0

        yAxis:
          gridLineColor: 'gray'
          stackLabels:
            style:
              color: 'white'
            enabled: false
            verticalAlign: 'middle'
            align: 'left'
            #formatter: ->
            #  categories[@x]

          title:
            text: "Total Number of Transactions"

        tooltip: 
          formatter: ->
             "Transactions:  " + @y
   
        plotOptions:
          series:
            stacking: 'normal'
            borderWidth: 0
            pointPadding: 0
            groupPadding: 0
          bar:
            colorByPoint: true
            cursor: "pointer"
            animation:
              duration: 2000
              easing: 'easeOutBounce'
            showInLegend: false
            dataLabels:
              enabled: true
              format: '{x}' + ': {y}'
              color: "white"
              align: 'left'
              verticalAlign: 'middle'
              style:
                fontSize: '17 px'
              connectorColor: "#000000"

        navigation:
          buttonOptions:
            verticalAlign: 'top'
            y: -7
            x: -9
            theme:
              'stroke-width': 1
              stroke: color
              r: 0
              fill: color
              states:
                hover:
                  fill: color
                select:
                  fill: color

        series: series
      )

  onData: (data) ->
    @createChart(data.series, data.categories, data.color)
</pre>

I'm a bit new to coffeescript/js in general so I apologize if the code doesn't look very nice. :kissing_smiling_eyes: But seeing as the chart only gets drawn when data is sent, I was wondering how to draw the chart upon load if data exists in the `history.yml` file?

Since the chart doesn't get drawn until it receives data, if the user refreshes the page there's nothing there, so I'd like to be able to load the chart with history.yml until data is received.

`history.yml:`
<pre>
instruments: |+
  data: {"series":[{"name":"Instruments","data":[292223,289424,216255,210580,184266,183860,180352,165023,148477,140018]}],"categories":["EEM - 2013-12-21 - 28.0 - PUT","EEM - 2013-12-21 - 35.5 - PUT","SPY - 2013-08-17 - 166.0 - PUT","SPY - 2013-08-17 - 167.0 - PUT","SPY - 2013-08-17 - 165.0 - PUT","JNJ - 2015-01-17 - 55.0 - CALL","SPX - 2013-09-21 - 1300.0 - PUT","SPY - 2013-08-17 - 166.0 - PUT","SPY - 2013-08-17 - 167.0 - PUT","SPY - 2013-08-17 - 166.0 - CALL"],"color":"#2c3e50","id":"instruments","updatedAt":1377504330}
</pre>

Thanks!

**Comment by cefigueiredo** [comment]
That issue seems old enough to be closed!
