### ISSUE TITLE
Having a masonry layout (Isotope) as opposed to gridster

### ISSUE THREAD

**Issue by divan-moller** [Shopify/dashing#215]
Possible enhancement: Would anyone be interested in working on implementing a masonry layout as an alternative to gridster? http://isotope.metafizzy.co/

Apart from the masonry layout the other extra features I would consider useful:
*filtering (only widgets in a certain state (error, warning, ok / selector based on class) as seen here: http://isotope.metafizzy.co/demos/combination-filters.html
*sorting
*hash history (based on filtering or sorting) http://isotope.metafizzy.co/demos/hash-history.html

**Comment by darkpixel** [comment]
Definitely not interested due to the licensing of isotope.  http://isotope.metafizzy.co/license.html

**Comment by tylermauthe** [comment]
Yeah, Masonry is not free for commercial use. I'd recommend closing this issue.

**Comment by pushmatrix** [comment]
Yeah decided not to go with Masonry for reasons mentioned above.
