### ISSUE TITLE
Pull data in to Dashing from a MySQL database

### ISSUE THREAD

**Issue by InTheScript** [Shopify/dashing#219]
Would be great if pulling data into Dashing from a MySql database was documented in here. and in the 'How Tos' Section. It's something I know a LOT of people who are unfamiliar with Ruby would love to know.

**Comment by lynchlee** [comment]
Well, i faced the problem same to @InTheScript , but the url can not be opened , http://wiki.manageditby.us/2013/08/09/dashing-labtech-agent-count-via-meter-widget/, should someone can help me ? thx !!
