### ISSUE TITLE
getting a error on 'dashing start'

### ISSUE THREAD

**Issue by chadvavra** [Shopify/dashing#22]
$ dashing start
config.ru:1:in `require': /Library/Ruby/Gems/1.8/gems/dashing-1.0/lib/dashing.rb:20: syntax error, unexpected ':', expecting $end (SyntaxError)
set server: 'thin', connections: [], history: {}
           ^
    from config.ru:1
    from /Library/Ruby/Gems/1.8/gems/rack-1.4.1/lib/rack/builder.rb:51:in`instance_eval'
    from /Library/Ruby/Gems/1.8/gems/rack-1.4.1/lib/rack/builder.rb:51:in `initialize'
    from config.ru:1:in`new'
    from config.ru:1

**Comment by adityai** [comment]
I am getting this error with ruby 1.9.3. Any suggestions?

**Comment by cefigueiredo** [comment]
It can not be the same error on ruby 1.9.3, if so, probably  you are using 1.8 without know about. 
Guess you use RVM on your user profile, and are having troubles starting dash by a script placed on `rc.d` or other similar unattended script runner engine.
