### ISSUE TITLE
Accessing Sinatra settings object from within a Job

### ISSUE THREAD

**Issue by grahamb** [Shopify/dashing#227]
Forgive me if this is obvious; I'm new to Sinatra and Ruby in general. How, if at all, can I access the Sinatra settings object from within a Job? I wanted to have some config settings stored in YAML files, so I added a method to config.ru to read them in and add them to settings. From within config.ru, I can access them (e.g. `settings.bamboo[:bamboo_host]` but from within a Job file I get a NoMethodError when trying to access `settings.bamboo`. When I try to access `settings.auth_token` or `settings.defaut_dashboard` from my Job, it returns `nil`.

Here's what I'm doing to read in the config files (from within the `configure` block in config.ru).

``` ruby
Dir.glob('config/*.yml').each do |f|
  config_name = File.basename(f, '.*')
  raw_config = File.read(f)
  config = YAML.load(raw_config).symbolize_keys
  set config_name.to_sym, Proc.new { config }
end
```

**Comment by cob16** [comment]
Instead of renaming you can use @sjernigans code at the end of configre do and before add
```
ENV["JOB_PATH"] = 'dashing can you wait a sec before you load the jobs?'
``` 
at the top of your file
