### ISSUE TITLE
New Relic with Dashing?

### ISSUE THREAD

**Issue by bstephenf** [Shopify/dashing#233]
I would like to monitor our dashboard using New Relic.  In their instructions, it asks you to save the newrelic.yml file to my 'config' directory.  With my out-of-the-box Dashing installation, I do not have a 'config' directory.

https://newrelic.com/docs/ruby/ruby-agent-installation

Does anyone have experience using New Relic with Dashing that can give me some guidance?

**Comment by amassaad** [comment]
I've just added this to the wiki @bubbajoelouis so I'll close this out. Thanks for outlining the solution! https://github.com/Shopify/dashing/wiki/Using-New-Relic-with-Dashing
