### ISSUE TITLE
Can dashing change style (e.g. background-color) depending of the job's value?

### ISSUE THREAD

**Issue by dkapanidis** [Shopify/dashing#24]
A simple use case of this would be to make a box color greenish when good values are given, and redish when bad values are given, giving a visual alert of things to notice.

It would be good to see a generic solution for existing widgets, or explain how a new widget could be implemented to do that.

**Comment by odrino14** [comment]
how can i use this for dashing-icinga2 ?
i want that my kachel-color for blue to red change when the count of critical is 1 or more
did someone have any idear ?
