### ISSUE TITLE
Can't start dashing (syntax error)

### ISSUE THREAD

**Issue by sujaymansingh** [Shopify/dashing#241]
Hi.

I've followed the steps at http://shopify.github.io/dashing/#setup.
(Albeit in a chef recipe.)

``` ruby
gem_package "dashing" do
  action :install
end
gem_package "bundler" do
  action :install
end
```

I created a new dashing app.

``` bash
vagrant@bigboard:/opt/bigboard$ dashing new dashboard
      create  dashboard
...
      create  dashboard/widgets/text/text.scss
```

And then (again via chef) called bundle.

``` ruby
execute "bundle for dashing app." do
  command "bundle"
  cwd "#{node[:bigboard][:path]}/dashboard"
end
```

However, I cannot start the app at all.

```
vagrant@bigboard:/opt/bigboard/dashboard$ dashing start
config.ru:1:in `require': /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/dashing-1.3.1/lib/dashing.rb:21: syntax error, unexpected ':', expecting $end (SyntaxError)
set server: 'thin', connections: [], history_file: 'history.yml'
           ^
    from config.ru:1
    from /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
    from /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
    from config.ru:1:in `new'
    from config.ru:1
vagrant@bigboard:/opt/bigboard/dashboard$
```

Do you have any idea what I'm doing wrong?
It's a standard ubuntu 12.04 box.

**Comment by adityai** [comment]
I am getting this error with version 1.9.3 and 2.2.0. Version of dashing installed is 1.3.4. Any suggestions?

**Comment by cefigueiredo** [comment]
As I answered you on #22 . It can not be the same error, because these mentioned errors are about ruby 1.9+ hash syntax. If you are really having this exactly error, your env are using ruby 1.8 and you doesn't know about. 
If you want get help, send us what u get running `ruby --version` and the error message you get when run `dashing start`

**Comment by adityai** [comment]
Carlos,
I realized later that the os had a version 1.8 by default. I changed it to version 1.9 and I was able to fire up a dashing dashboard.

Thank you,
Aditya.
