### ISSUE TITLE
Dashing no longer functions on Heroku

### ISSUE THREAD

**Issue by yllus** [Shopify/dashing#304]
The dashboards I've deployed to Heroku, and the sample dashboards that you can view below, no longer seem to display data:
- http://dashingdemo.herokuapp.com/sample
- http://dashingdemo.herokuapp.com/sampletv

I haven't changed my dashboards in any way and they're ceased functioning; I'm wondering if this is some sort of new incompatibility or security restriction on Heroku's end.

**Comment by abepetrillo** [comment]
Passenger didn't help speed up anything for me on Heroku. Although I am using one dyno...

**Comment by tomcoonen** [comment]
@ssalinas @yllus old issue, but still relevant, it did the trick on Heroku.

**Comment by binarymason** [comment]
yep, still works.  thanks @yllus and @ssalinas
