### ISSUE TITLE
Run dashing behind a reverse proxy (with path prefix)

### ISSUE THREAD

**Issue by Sjlver** [Shopify/dashing#319]
I'm trying to run dashing behind a reverse proxy. I'm using the following proxy settings:

```
ProxyPass        /dashboard http://myhost:3030/dashboard
ProxyPassReverse /dashboard http://myhost:3030/dashboard
```

In order to account for the `/dashboard` prefix, I tried modifying config.ru as follows:

```
map '/dashboard' do
  map Sinatra::Application.assets_prefix do
    run Sinatra::Application.sprockets
  end

  run Sinatra::Application
end
```

There are several problems with this approach:
- accessing /dashboard redirects to /foo (where foo is the name of a board) instead of /dashboard/foo
- paths in /dashboard/layout.erb are hardcoded (e.g. /assets/application.js)

I presume much of this could be solved by using the right Sinatra URL helpers. But then, I don't have much experience with Sinatra...

Any suggestions?

**Comment by odrino14** [comment]
@Sjlver did u find a solution for that. i am having the same problem

**Comment by Sjlver** [comment]
@odrino14 I think with the documentation pointed to by mcritchlow, it should work.

**Comment by odrino14** [comment]
i tried it with taht but it is not working

**Comment by odrino14** [comment]
@Sjlver it is not working. i get `Drats! That Dashboard doesn't exist.`
did u make something else i don't know where to look
