### ISSUE TITLE
httparty load error

### ISSUE THREAD

**Issue by SelimBudakoglu** [Shopify/dashing#329]
Hi guys,
I have been trying to make get request from sample.rb file with HTTParty. httparty and json installed however when I try to star dashing with "dashing start" I am getting the error below. Any idea?
Thanks in advance.
=============================
sample.rb
=============================
require 'httparty'
require 'json'

current_valuation = 0
current_karma = 0

SCHEDULER.every '2s' do

  response = HTTParty.get('https://graph.facebook.com/zuck')
  body = JSON.parse(response.body)
  id = body["id"]
  
  logger.debug(id)

  last_valuation = current_valuation
  last_karma     = current_karma
  current_valuation = rand(100)
  current_karma     = rand(500)

  send_event('valuation', { current: current_valuation, last: last_valuation })
  send_event('karma', { current: current_karma, last: last_karma })
  send_event('synergy',   { value: id })
end

=============================
ERROR
=============================
C:\sweet_dashboard_project>dashing start
C:/Ruby193/lib/ruby/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:i
n `require': cannot load such file -- httparty (LoadError)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/backports-3.6.0/lib/backports/t
ools.rb:343:in `require_with_backports'
        from C:/sweet_dashboard_project/jobs/sample.rb:1:in `<top (required)>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/backports-3.6.0/lib/backports/t
ools.rb:343:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/backports-3.6.0/lib/backports/t
ools.rb:343:in `require_with_backports'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/dashing-1.3.2/lib/dashing.rb:16
7:in `block in <top (required)>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/dashing-1.3.2/lib/dashing.rb:16
7:in `each'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/dashing-1.3.2/lib/dashing.rb:16
7:in `<top (required)>'
        from config.ru:1:in `require'
        from config.ru:1:in `block in <main>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:
55:in `instance_eval'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:
55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/thin-1.6.2/lib/rack/adapter/loa
der.rb:33:in `eval'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/thin-1.6.2/lib/rack/adapter/loa
der.rb:33:in `load'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/thin-1.6.2/lib/thin/controllers
/controller.rb:182:in `load_rackup_config'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/thin-1.6.2/lib/thin/controllers
/controller.rb:72:in `start'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/thin-1.6.2/lib/thin/runner.rb:1
99:in `run_command'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/thin-1.6.2/lib/thin/runner.rb:1
55:in `run!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/thin-1.6.2/bin/thin:6:in `<top
(required)>'
        from C:/Ruby193/bin/thin:23:in `load'
        from C:/Ruby193/bin/thin:23:in `<main>'

**Comment by tylermauthe** [comment]
Please close this issue.
