### ISSUE TITLE
Changing Background Color of Text Image

### ISSUE THREAD

**Issue by derwin12** [Shopify/dashing#336]
Sorry this is a bit of a rehash #161 ..

I tried adding this to text.coffee

  onData: (data) ->
    if data['background-color']
      $(@get('node')).css 'background-color', data['background-color']

restarted Dashing.. then tried
curl -d '{  blahblahblah, "background-color": "yellow" }'  http://blah:3030/widgets/textbox32

With nothing changing in the background color. Is there more to making this functionality work?

**Comment by tylermauthe** [comment]
Please close this issue.
