### ISSUE TITLE
Some widgets update continuously, some do not, when passed data

### ISSUE THREAD

**Issue by zuzzyuk** [Shopify/dashing#338]
Hi, I have the latest dashing pulled down 3 days ago (~20th March 2014) and I have a java app that pushes (POSTs) data into my new shiny test dashboard.  I have two widgets, a meter and a graph, and I am pushing the same data to both (the meter I am passing a single value, the graph that same value and the 9 previous values, plus x labels).

The graph seems to update every time data is pushed, which is every 10s at the moment.  The meter seems to refresh once or twice then ceases to update when data is pushed to it.  

However, it all comes back to life when I push a reload event to the dashboard, which I do every couple of minutes while testing, and the meter then works happily for another couple of updates, then stops again.  

I have debug on in application.coffee and I can see successful POSTs to both widgets every few seconds, so the data is fine.

Now it should be said that my laptop is significantly overcommitted with its VMs its running and the old Fedora 16 Linux VM I'm running dashing on is a tad laggy but hardly noticeably.  I'd understand a slight delay but not it just not happening?

I'm displaying the dashboard on my laptop main OS (Mac OSX, using both Chrome and FF) 

Any suggestions?

**Comment by tylermauthe** [comment]
Please close this issue.
