### ISSUE TITLE
Help with reading Oracle data into a widget

### ISSUE THREAD

**Issue by derwin12** [Shopify/dashing#344]
Can someone provide a google reference to assist a novice (me) trying to read Oracle data into a widget. I have only seen mysql references. [edit] This works! [edit2] fix a bug..

Something like this:

require 'oci8'

SCHEDULER.every '15m', :first_in => 0 do |job|

  conn = OCI8.new('user','password','connectstr')
  sql = "select col1, ncol2 from emp where rownum < 6"

  cursor = conn.exec(sql) 
  cursor.define(1, String, 30)
  cursor.define(2, Integer)
  rowitems = []

  while r = cursor.fetch()
    rowitems << {
      :label => r[0],
      :value => r[1]
    }
  end  

  send_event('somewidget', { items: rowitems } )
  puts rowitems
  cursor.close()

end
conn.logoff

**Comment by kondalonline** [comment]
I am getting below error. I have oci8 installed.  Can you throw some light as what is wrong here

---

gem list ruby-oci*
**\* LOCAL GEMS ***

## ruby-oci8 (2.2.2)

irb
2.3.1 :001 > require 'oci8'
Warning: NLS_LANG is not set. fallback to US7ASCII.
 => true

---

Error

---

/usr/local/rvm/gems/ruby-2.3.1/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require': cannot load such file -- oci8 (LoadError)
    from /usr/local/rvm/gems/ruby-2.3.1/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in`require_with_backports'
    from /opt/rundeck/jobs/convergence.rb:2:in `<top (required)>'

**Comment by kondalonline** [comment]
I have added below line to Gem file. This resolved the problem
gem 'ruby-oci8'
