### ISSUE TITLE
Custom Widget? Help?

### ISSUE THREAD

**Issue by samc123321** [Shopify/dashing#353]
Hi All

Is it possible to create a widget that presents data from the following webpage?

http://helpdesk.eastquayit.net:8080/conn1.aspx

I really would like a simple webpage that would show these open tickets on the screen and be updated when they close? 

I am rubbish at coding, any help would be great.

Thanks

Sam

**Comment by danggrianto** [comment]
add this `set :protection, :except => :frame_options` on `config.ru`
