### ISSUE TITLE
Widgets not appearing when using .haml dashboard files

### ISSUE THREAD

**Issue by darkmoves** [Shopify/dashing#354]
I've converted my dashboard files from .erb to .haml after installing the 'haml' gem and requiring it upon initialization. The correct HTML is being rendered in the browser but the widgets aren't appearing. When I switch back over to .erb files, everything works fine. Is there any additional configuration that I need to do in order to use haml?

**Comment by joallard** [comment]
![](http://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)
