### ISSUE TITLE
Dynamically Set data-max value in html.erb file

### ISSUE THREAD

**Issue by matt-murdock** [Shopify/dashing#355]
Hello, I asked this question at https://github.com/gottfrois/dashing-rails and they sent me here. Regarding the "Meter" widget, is there a way to dynamically set the data-max attribute value inside the div element within sample.erb? I want to use the meter for capacity and as we get more capacity that data-max value would change. According to the coffee file for that widget here :
https://github.com/gottfrois/dashing-rails/blob/22a81fb4df3732879ed1afb05ba404aec5860a23/vendor/assets/javascripts/dashing/default_widgets/meter.coffee

It does not look like I can send a max value in the send_event call

**Comment by tylermauthe** [comment]
Please close this issue.
