### ISSUE TITLE
How can I make a widget clickable?

### ISSUE THREAD

**Issue by blysik** [Shopify/dashing#36]
Hi,

I'd like to be able to set an href for a widget.  Is this possible?

**Comment by spuder** [comment]
Confirmed, `onclick="location.href='myurl'" ` works.

**Comment by thoughtcroft** [comment]
I know this is an old issue but I used the `onclick=` method and that works fine except not on an iOS device. Anyone work out the fix required for that?

**Comment by DeanCording** [comment]
One problem with this solution is that moving the widget triggers the onclick call, making it impossible to re-arrange the dashboard.

**Comment by phylor** [comment]
@thoughtcroft Dashing uses gridster to move widgets around. There is an [open issue for click events on iOS devices](https://github.com/ducksboard/gridster.js/issues/132) over at gridster.

The temporary fix is to use `pushmatrix`'s solution and to additionally register for `touchend` events. The `click` event works on most devices and the `touchend` event on iOS.

I'm successfully using following code to achieve the same behavior on desktops and iOS:

    <script type='text/javascript'>
      function openUrl(obj) {
        var widget = $(obj).find('.widget');
        var url = widget.data('url');
        window.open(url, '_blank');
      }

    $(function() {
       $('li').live('click', function(e){
        openUrl(this);
      });
      $('li').live('touchend', function(e){
        openUrl(this);
      });
    });
    </script>
