### ISSUE TITLE
JSON data to graph widget

### ISSUE THREAD

**Issue by pranavjain02** [Shopify/dashing#363]
I am trying to send json data to the graph but its not reflecting on the UI.
I have created a widget cpuinfo and I explicitly want myself to push data that widget.
What I am doing is -

curl -d '{ "auth_token": "XXXX","series": {"datapoints": [[0.1, 1401087310], [0.5, 1401087320], [0.1, 1401087330]]}}' http://localhost:3030/widgets/cpuinfo

But there is no reflection of data on the UI.

Please correct me if I am making any syntax error.

**Comment by tylermauthe** [comment]
It looks like you're doing everything correctly, I suspect the widget you've created has some issues. Perhaps this may be of use: https://github.com/Shopify/dashing/wiki/How-To:-Debug-incoming-widget-data

Please close this issue.
