### ISSUE TITLE
Connecting Dashing to MongoDB

### ISSUE THREAD

**Issue by bubbajoelouis** [Shopify/dashing#368]
I am interested in connecting a Dashing instance to a local MongoDB to store data events sent in via curl and created by jobs. app.rb seems like a good location to insert events into a JSON data store. I was thinking to add something like the following to the send_event function:

body[:updatedAt] ||= Time.now.to_f # Adds milliseconds
..
Sinatra::Application.settings.connections.each { |out| out << event }

collection = @db.collection(id)
insert = collection.insert(event)

This assumes a database connection object named @db. 

1) Does this approach seem valid?
2) I am not certain where to set up the official MongoDB connection. Should it be within app.rb? cli.rb?

Thank you!
BJL

**Comment by tylermauthe** [comment]
This is way outside of the scope of what Dashing does and should do (IMHO)...

This seems like a job for Graphite or similar. Also, why MongoDB?

That being said, that's approximately where I'd add such functionality -- though I'd probably break it out into a `persist_event_to_db` method.

**Comment by amassaad** [comment]
Exactly, I think the best approach would be to create the connection to MongoDB with a separate app and send events to your dashboard using the API but you could also write a job similar to: https://github.com/Shopify/dashing/wiki/How-to:-send-mysql-data-to-your-widgets
