### ISSUE TITLE
Rotating dashboards

### ISSUE THREAD

**Issue by GreatPotato** [Shopify/dashing#369]
We've setup lots of dashing dashboards - different departments need different data. This all works great out of the box.

What we'd really like to do is have our management to rotate between all dashboards - is there anyway to do this? Would this be something to make the browser do instead? Not sure on the best approach for this...

Would love your thoughts!

**Comment by tylermauthe** [comment]
There are a number of options in this list: https://github.com/Shopify/dashing/wiki/Additional-Widgets#other-third-party-tools

Please close this issue.

**Comment by cpg** [comment]
@protomouse Did you document anywhere how to run dashboards as slim? That would be very useful.

I tried the obvious, adding slim to the Gemfile and renaming the dashbaords to .html.slim or just .slim,and it does not seem to work. I see that you include the parts of a dashboard, however, how does the layout and the main entry point for a dashboard?
