### ISSUE TITLE
Nothing Displays on Internet Explorer

### ISSUE THREAD

**Issue by sikosis** [Shopify/dashing#37]
Just thought I'd mention that nothing shows up when you try to use IE as the browser for dashing.

Reason this came up, is we were trying to use a screensaver that uses the IE browser to show the page.

**Comment by larrycai** [comment]
@centic9 very good direction for this.

And your sample doesn't work for IE11 like, I refer to the sto: http://stackoverflow.com/questions/19999388/jquery-check-if-user-is-using-ie which is more complete.
