### ISSUE TITLE
Initial value in Number widget

### ISSUE THREAD

**Issue by zcarson** [Shopify/dashing#371]
When I browse to my dashboard, my number widget is empty until the next time the scheduler fires. This occurs each time I load up a dashboard.

Does it always work that way? I feel like it should know the value before the next scheduled refresh.

**Comment by howardsternisbatman** [comment]
I had the same problem. This thread solved it!

thanks.

**Comment by howardsternisbatman** [comment]
I found this thread & it solved the color problem
https://github.com/Shopify/dashing/issues/423
