### ISSUE TITLE
Heroku Slow And Unstable

### ISSUE THREAD

**Issue by ahanmal** [Shopify/dashing#372]
Hi,

I deployed my dashboard to a Heroku free dyno. I am pinging it every few minutes to make sure it is always alive. My dashboard has 9 jobs, 10 widgets, and runs using Passenger, and seems to be slow to start up on Heroku. About once per day, I get an "Application Error" and need to go back and reload it a few times from my computer, then reset my Chromecast(running via https://github.com/dryan/geckocast). Is this normal? How about OpenShift? I get three free "small gears", would a 2 or 3 gear system be better for Dashing?

Thanks,
ahanmal

**Comment by tylermauthe** [comment]
Heroku free dynos will spin down if not in use and are generally unreliable. It looks like OpenShift doesn't idle as frequently: http://stackoverflow.com/questions/23795884/how-long-with-no-traffic-before-an-openshift-gear-goes-idle

You may have better luck with some gears... Alternatively, you could run it locally. It doesn't need much processing power, a Raspberry Pi would be lots.
