### ISSUE TITLE
Microsoft SQL Query

### ISSUE THREAD

**Issue by around01** [Shopify/dashing#377]
We'd like to query a Microsoft SQL Server database and display on Dashing.  Is there a widget or an example that will show me how to go about doing this.

**Comment by charlievogt** [comment]
I'm new at linux.  When I try to run

**Comment by MartynKeigher** [comment]
Try running ```sudo apt-get update && sudo apt-get -y upgrade``` first, and then try ```apt-get install -y freetds-dev``` again.

**Comment by charlievogt** [comment]
Thanks!  That seemed to help, along with a change to my sources.list file.  When I try to start dashing, it's giving me this error:

`dashing start
/var/lib/gems/1.9.1/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require': /home/cvogt/test_dashboard/jobs/MYJOB.rb:15: syntax error, unexpected $end, expecting keyword_end (SyntaxError)
        from /var/lib/gems/1.9.1/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:157:in `block in require_glob'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:156:in `each'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:156:in `require_glob'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:167:in `<top (required)>'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing.rb:3:in `require'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing.rb:3:in `<top (required)>'
        from config.ru:1:in `require'
        from config.ru:1:in `block in <main>'
        from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
        from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `eval'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `load'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:72:in `start'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
        from /usr/local/bin/thin:23:in `load'
        from /usr/local/bin/thin:23:in `<main>' `

My job file is 

`
#!/bin/env ruby
# encoding: utf-8

require 'tiny_tds'

SCHEDULER.every '300s', :first_in => 0 do |job|

client = TinyTds::Client.new(:username => 'MYUSER', :password => 'MYPASSWORD', :host => 'MYHOST', :database => 'MYDB', :port => '1433')
 rs = client.execute("SELECT Caption, IP_Address, Description, Vendor, StatusLED, StatusDescription, LastSync, LastSystemUpTimePollUtc
  FROM [MYDB].[Nodes]
  WHERE StatusLED LIKE '%down%'
  ORDER BY LastSystemUpTimePollUtc, Caption;")
 rs.each do |row|
  send_event('list', {value: row['value'] })
 client.close
`

Is there something glaringly obvious that I'm doing incorrectly?  Thanks again for your help!

**Comment by charlievogt** [comment]
Thanks! That seemed to help, along with a change to my sources.list file. When I try to start dashing, it's giving me this error:

        cvogt@dashboard:~/test_dashboard$ dashing start
    /var/lib/gems/1.9.1/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require': /home/cvogt/test_dashboard/jobs/MYJOB.rb:15: syntax error, unexpected $end, expecting keyword_end (SyntaxError)
        from /var/lib/gems/1.9.1/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:157:in `block in require_glob'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:156:in `each'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:156:in `require_glob'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:167:in `<top (required)>'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing.rb:3:in `require'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing.rb:3:in `<top (required)>'
        from config.ru:1:in `require'
        from config.ru:1:in `block in <main>'
        from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
        from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `eval'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `load'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:72:in `start'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
        from /usr/local/bin/thin:23:in `load'
        from /usr/local/bin/thin:23:in `<main>'

My job file looks like this:

    #!/bin/env ruby
    # encoding: utf-8

    require 'tiny_tds'

    SCHEDULER.every '300s', :first_in => 0 do |job|

    client = TinyTds::Client.new(:username => 'MYUSER', :password => 'MYPASSWORD', :host => 'MYHOST', :database => 'MYDB', :port => '1433')
     rs = client.execute("SELECT Caption, IP_Address, Description, Vendor, StatusLED, StatusDescription, LastSync, LastSystemUpTimePollUtc
      FROM [MYDB].[Nodes]
      WHERE StatusLED LIKE '%down%'
      ORDER BY LastSystemUpTimePollUtc, Caption;")
     rs.each do |row|
      send_event('list', {value: row['value'] })
     client.close


Is there something glaringly obvious that I'm doing incorrectly? Thanks again for your help!

**Comment by tylermauthe** [comment]
You have a couple syntax error, you need to add two `end`'s after the client.close.

In Ruby, when you say "do |x, y, z|" you are beginning a block (kind of like an anonymous function / lambda). You must close it by saying "end".

You might also find this interesting: https://github.com/bbatsov/ruby-style-guide

So:
```ruby
#!/bin/env ruby
# encoding: utf-8

require 'tiny_tds'

SCHEDULER.every '300s', :first_in => 0 do |job|
  client = TinyTds::Client.new(:username => 'MYUSER', :password => 'MYPASSWORD', :host => 'MYHOST', :database => 'MYDB', :port => '1433')
  rows = client.execute("SELECT Caption, IP_Address, Description, Vendor, StatusLED, StatusDescription, LastSync, LastSystemUpTimePollUtc
    FROM [MYDB].[Nodes]
    WHERE StatusLED LIKE '%down%'
    ORDER BY LastSystemUpTimePollUtc, Caption;")
  rows.each do |row|
    send_event('list', {value: row['value'] })
    client.close
  end
end
```

**Comment by charlievogt** [comment]
Thank you very much!  Can anyone offer feedback for how to change this from reporting to the "Hotness" widget to get it to go into the "list" widget?  Thanks, again!  You are all very helpful!

**Comment by tylermauthe** [comment]
The first parameter in your `send_event` call defines the `data-id` that will receive the event. This must correspond to the `data-id` value specified in your dashboard.erb file.

**Comment by MartynKeigher** [comment]
Here is a copy/paste of a working MSSQL job. Change it to fit your need... 

```SCHEDULER.every '300s', :first_in => 0 do |job|


client = TinyTds::Client.new(:username => 'fred', :password => 'P@ssword', :host => '192.168.1.1', :database => 'abc', :port => '1433')
 rs = client.execute("SELECT count(*) as value FROM [abc].[dbo].[SR_Service]WHERE SR_Board_RecID = \'36\' AND Date_Closed IS null AND SR_Status_RecID != \'475\' ")
 rs.each do |row| 
  send_event('foo', {value: row['value'] })
 end
 client.close

end```

Hope that helps you out a bit.

**Comment by MayurMittal** [comment]
@MartynKeigher Hello. I hope you are still active on Dashing. I have installed dashing on Windows 7 64bit and running Ruby 2.3.0. I an trying to connect with the MSSQL database using the above code. But as soon as I type Dashing Start the following error comes in, not sure what I am missing, I am new to technology, so please forgive me if something is not correct :- 

`C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require': cannot load such file -- tiny_tds/tiny_tds (LoadError)
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/tiny_tds-2.0.0-x86-mingw32/lib/tiny_tds.rb:26:in `rescue in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/tiny_tds-2.0.0-x86-mingw32/lib/tiny_tds.rb:29:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from C:/Sites/monitorama/jobs/mssql.rb:1:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/dashing-1.3.7/lib/dashing/app.rb:171:in `block in require_glob'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/dashing-1.3.7/lib/dashing/app.rb:170:in `each'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/dashing-1.3.7/lib/dashing/app.rb:170:in `require_glob'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/dashing-1.3.7/lib/dashing/app.rb:181:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/dashing-1.3.7/lib/dashing.rb:3:in `require'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/dashing-1.3.7/lib/dashing.rb:3:in `<top (required)>'
        from config.ru:1:in `require'
        from config.ru:1:in `block in <main>'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.3.0/bin/thin:22:in `load'
        from C:/RailsInstaller/Ruby2.3.0/bin/thin:22:in `<main>'`

Installed various versions of tiny_tds not sure which is the correct one :(
1. tiny_tds-0.6.2.pre.beta1-x64-mingw32
2. tiny_tds-1.1.0-x86-mingw32
3. tiny_tds-2.0.0-x64-mingw32
4. tiny_tds-2.0.0-x86-mingw32

By mssql.rb file is 

`require 'tiny_tds'

SCHEDULER.every '300s', :first_in => 0 do |job|

client = TinyTds::Client.new(:username => 'XX', :password => 'XX', :host => 'dev.test.ab.com', :database => 'Dashboard', :port => '1433')
 rs = client.execute("select parentvendor from [dbo].[PulledIntegrationDetails] where live_date is null ")
 rs.each do |row| 
  send_event('test', {value: row['value'] })
 end
 client.close
 end`

and my gem file is 
`source 'https://rubygems.org'
gem 'dashing'
gem 'tiny_tds'
`

I have also installed freetds
`PS C:\> tsql -c
[TinyTds][v2.0.0][tsql]: C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/tiny_tds-2.0.0-x86-mingw32/ports/i686-w64-mingw32/freetds/1.00.27/bin/tsql.EXE
C:\RailsInstaller\Ruby2.3.0\lib\ruby\gems\2.3.0\gems\tiny_tds-2.0.0-x86-mingw32\ports\i686-w64-mingw32\freetds\1.00.27\bin\tsql.EXE: unknown option -- c
Usage:  C:\RailsInstaller\Ruby2.3.0\lib\ruby\gems\2.3.0\gems\tiny_tds-2.0.0-x86-mingw32\ports\i686-w64-mingw32\freetds\1.00.27\bin\tsql.EXE [-a <appname>] [-S <server> | -H <hostname> -p <port>] -U <username> [-P <password>] [-I <config file>] [-o <options>] [-t delim] [-r delim] [-D database]
        C:\RailsInstaller\Ruby2.3.0\lib\ruby\gems\2.3.0\gems\tiny_tds-2.0.0-x86-mingw32\ports\i686-w64-mingw32\freetds\1
.00.27\bin\tsql.EXE -C
Options:
        f       Do not print footer
        h       Do not print header
        t       Print time informations
        v       Print TDS version
        q       Quiet

        Delimiters can be multi-char strings appropriately escaped for your shell.
        Default column delimitor is <tab>; default row delimiter is <newline>`  

I will be glad if you can help me in this.
