### ISSUE TITLE
How to debug in Eclipse/etc?

### ISSUE THREAD

**Issue by sinayion** [Shopify/dashing#381]
I am trying to debug the ruby jobs in Eclipse, so I can track variable values in the code. The Ruby debugger in Eclipse throws an error when it reaches SCHEDULER.every, so I can't track calculations done within it.

How do I get Eclipse to behave here, or do I need to debug with something else? Note, I set `Dashing.debugMode = true` in application.coffee, found in another issue here; but I'll be honest, I do not understand fully what this does.

Thanks for any help you can provide.

**Comment by tylermauthe** [comment]
application.coffee defines the front-end code, so it is only turning on debugging in the browser. It has no effect on the Rufus jobs.

What is the error that Eclipse throws?

**Comment by tylermauthe** [comment]
Please close this issue.
