### ISSUE TITLE
widget is not appearing in mac.

### ISSUE THREAD

**Issue by santhoshjoy** [Shopify/dashing#382]
I created a project and ran the buddle. when I tried to hit the localhost:3030 . I am seeing a message with "Try this: curl -d '{ "auth_token": "YOUR_AUTH_TOKEN", "text": "Hey, Look what I can do!" }' \http://localhost:3030/widgets/welcome", with a black screen in background. I tried in Firefox,Chrome and Safari. Please help me

**Comment by tylermauthe** [comment]
Please close this issue.
