### ISSUE TITLE
Font-awesome 4.xxx update?

### ISSUE THREAD

**Issue by howardsternisbatman** [Shopify/dashing#386]
hello,

I'm running dashing on a raspberry pi. Having difficulties upgrading to the newest awesome fonts. They seem to install ok but I can't make them actually appear on the dashboard.  Any thoughts?

Here are the results of bundle

Using rake 0.9.2.2
Using i18n 0.6.9
Using json 1.8.1
Using minitest 5.3.4
Using thread_safe 0.3.4
Using tzinfo 1.2.1
Using activesupport 4.1.1
Using builder 3.2.2
Using erubis 2.7.0
Using actionview 4.1.1
Using rack 1.5.2
Using rack-test 0.6.2
Using actionpack 4.1.1
Using addressable 2.3.6
Using backports 3.6.0
Using buftok 0.2.0
Using coffee-script-source 1.7.0
Using execjs 2.0.2
Using coffee-script 2.2.0
Using daemons 1.1.9
Using rufus-scheduler 2.0.24
Using sass 3.2.19
Using rack-protection 1.5.3
Using tilt 1.4.1
Using sinatra 1.4.5
Using multi_json 1.10.1
Using sinatra-contrib 1.4.2
Using hike 1.2.3
Using sprockets 2.10.1
Using eventmachine 1.0.3
Using thin 1.6.2
Using thor 0.18.1
Using dashing 1.3.4
Using equalizer 0.0.9
Using multipart-post 2.0.0
Using faraday 0.9.0
Using railties 4.1.1
Using font-awesome-rails 4.1.0.0
Using htmlentities 4.3.2
Using http_parser.rb 0.6.0
Using http 0.6.1
Using memoizable 0.4.2
Using mini_portile 0.6.0
Using naught 1.0.0
Using nokogiri 1.6.2.1
Using simple_oauth 0.2.0
Using twitter 5.11.0
Using xml-simple 1.1.3
Using bundler 1.6.2

**Comment by captn3m0** [comment]
Facing the same issue. @apsdehal found some workarounds, though.

**Comment by tylermauthe** [comment]
You have installed font-awesome-rails.

This is not a Rails application.

You want font-awesome-sass.

Follow the instructions here: https://github.com/FortAwesome/font-awesome-sass

In particular, do not forget to do this in your application.scss:
```sass
@import "font-awesome-sprockets";
@import "font-awesome";
```
