### ISSUE TITLE
HighBar widget

### ISSUE THREAD

**Issue by santhoshjoy** [Shopify/dashing#391]
I added the below widget which is a bar chart "Transactions by Exchange". I placed all the supporting files with the highbar folder, Update dashboards and jobs code as well. I am only seeing the background color with the caption. No data at all. Is there anything I have to do anything apart from this.

http://titanium-edge.herokuapp.com/edge
https://github.com/mikechau/titanium_edge

**Comment by tylermauthe** [comment]
Do you get errors in your browser's console? Sounds like Highbar is failing to load.

**Comment by tylermauthe** [comment]
Please close this issue.
