### ISSUE TITLE
Cant change meter color

### ISSUE THREAD

**Issue by tes5884** [Shopify/dashing#392]
Hi,
I apologize if this is the wrong forum.
This is my current dashboard.
![2014-07-01_1210](https://cloud.githubusercontent.com/assets/1878642/3445806/d7a43a1e-013a-11e4-847f-35f601545f6a.png)

I'm trying to change the default "green" to a darker color.

I tried changing the "$background-color" value in "meter.scss", that didn't change anything.

What am I missing? Can someone please point me in the right direction?

This project is amazing!

Thanks!
Tzvi

**Comment by tylermauthe** [comment]
Add a data-bgcolor property on the widget in your Dashboad .erb file. This enables you to specify different colours for individual widgets.
