### ISSUE TITLE
Deploying Sample dashboard on Heroku does not update widgets

### ISSUE THREAD

**Issue by leapmotion-services** [Shopify/dashing#395]
Hi,

I can see that Shopify's sample dashboard is functional on Heroku:

http://dashingdemo.herokuapp.com/sample

However, I made an even simpler dashboard. Basically I removed all the widgets from sample.erb and only left the Graph widget. Everything else is the same. That is, this graph widget is fed by a scheduler script in jobs/convergence.rb. I merely changed this script to add a "puts" statement to see the data set being plotted.

Here is the simplified dashboard on heroku that I deployed:

http://sample-metrics-dashboard.herokuapp.com/sample

Notice a couple of things:

1) When you first click the link, the widget is just empty. Even though the scheduler that feeds this graph generates random integers every 2 seconds, the widget stays empty for several minutes.

Looking at the logs, I found on Heroku I found this whenever I refresh the browser to see if that would update the widget (but it still remains empty):

2014-07-09T01:55:08.365401+00:00 heroku[router]: at=error code=H18 desc="Request Interrupted" sock=client method=GET path="/events" host=sample-metrics-dashboard.herokuapp.com request_id=e3ebbdff-188a-4057-97a8-f32b05133183 fwd="173.247.193.180" dyno=web.1 connect=2 service=402945 status=503 bytes=646
2014-07-09T01:55:08.362379+00:00 app[web.1]: 173.247.193.180 - - [09/Jul/2014 01:55:08] "GET /events HTTP/1.1" 200 - 402.9460

2) I added a log to convergence.rb to print out the data set being plotted every 2 seconds. On my localhost, this log gets printed every 2 seconds as expected but in Heroku, I don't see it printed and when it does, it comes in batches. This makes me think that is why the widget isn't being updated every 2 seconds like it should.

Any help would be much appreciated. I also compared the gem versions in my Gemfile.lock to what is listed her in the repo:

https://github.com/Shopify/dashing/blob/master/dashing.gemspec

The versions match.

Cheers,

Prathap

**Comment by tylermauthe** [comment]
This URL is now protected. I suspect you have solved your issue.

Please close this.
