### ISSUE TITLE
Rickshawgraph background colors starting with "F" cause page to die

### ISSUE THREAD

**Issue by EllenSebastian** [Shopify/dashing#397]
If you edit Rickshawgraph.scss to have a background-color starting with F, for example: 

``` 
$background-color:  #ff5050;
```

this causes pages to die ("Aw snap" page on Chrome). 
My guess is there's an off-by-one/edge case error in the logic that uses the background color to calculate data colors in rickshawgraph.coffee.
This is easily avoidable by choosing a similar color that does not start with F. 

I'd guess this is the case for other widgets like Graph as well, but I haven't checked.

**Comment by tylermauthe** [comment]
This is not true for standard Dashing widgets. Perhaps it was true for a dark period of time when Chrome had a ridiculously terrible bug.

If this is still happening for the Rickshawgraph widget (although I am dubious of this), you should submit a request for support here: https://gist.github.com/jwalton/6614023
