### ISSUE TITLE
onData event not firing

### ISSUE THREAD

**Issue by gchendry** [Shopify/dashing#401]
Trying out things with the sample dashboard, trying to get things to dynamically change.
I cannot get onData event to fire after initial startup, all I have is a console log saying that it is "here", and no errors in the console when running. Tried this on Text and List widgets

**Comment by tylermauthe** [comment]
Have you created any jobs?

As you can see in [Dashing.coffee](https://github.com/Shopify/dashing/blob/16b4c4c3d8e6636521c702873ab2066bf7977a53/javascripts/dashing.coffee#L58-L63), the onData method is called whenever receiveData is called on a widget. receiveData is triggered whenever a message is received from the EventSource. If `/events` is not returning any data, your widgets won't get any data and the onData function will not trigger.

**Comment by tylermauthe** [comment]
Please close this issue.
