### ISSUE TITLE
Send External Link to Widgets Through Job

### ISSUE THREAD

**Issue by bubbajoelouis** [Shopify/dashing#403]
Greetings!

I need to send an external URL from a Dashing Job to a Number (or any) Widget.

My Job loads a URL into a string named 'link'. It then builds the onclick string:

       my_onclick = "location.href=\'#{link}\'"

This is added to the send_event:

       send_event("top10_#{num}", { current: num, moreinfo: my_moreinfo, status: current_status, title: my_title, onclick: my_onclick } )

The onclick appears in the JavaScript Console of Chrome:

{ current: 12, moreinfo: "Manager Name", status: "danger", title: Network Monitoring", onclick: "location.href='http://...'" }

But does not make it into the HTML:

    <li data-row="4" data-col="2" data-sizex="1" data-sizey="1"
	>
      <div data-id="top10_12" data-view="Number"
	></div>
    </li>

Of course if i hard code the onclick into the <div>, it works:

      <div data-id="hard_code_test" data-view="Number"
        data-title="URL Test"
        data-moreinfo="Clicking This Widget Links Elsewhere"
        onclick="location.href='http://en.wikipedia.org/wiki/dashing'"
      ></div>

But i need to load the URL from an external data source and pass it to the Widget.

I believe the Widget's coffeescript needs to be modified, but could anyone please post the full example code that would need to be added for this to work? Just answering with "Just put onclick: ->" won't really clear it up for me. :) I would also appreciate pointing me to what documentation i should read to learn this.

  onClick: ($data) ->
    if @get('onclick')
      url = @get('onclick')

I can change the string in the Job to send simply the URL instead of the "location.href=http...". Would it need to be sent in the send_event with { ..data-onclick: link }?

Thank you!
BJL;)

**Comment by tylermauthe** [comment]
Dashing uses Batman.js at its core and you can use [Batman's view bindings](http://batmanjs.org/docs/api/batman.view_bindings.html) to achieve this.

In the Widget's .html file, you need to add a `data-bind-onclick="onclick"` attribute.
