### ISSUE TITLE
Zendesk Integration

### ISSUE THREAD

**Issue by curiouscrusher** [Shopify/dashing#407]
I'm looking into writing a simple widget to show incoming/active/ tickets from Zendesk. And once that works move into other features. The documentation for the Zendesk API is thorough, however I'm not sure where to start on the Dashing side as far as the app layout. Has anybody looked into or tried this before?

**Comment by tylermauthe** [comment]
You can use this as an example: https://gist.github.com/Skeyelab/9bc044bc7f68aa365157

**Comment by tylermauthe** [comment]
Please close this issue.
