### ISSUE TITLE
Widget data only displayed after stopping dashboard (Mac OSX 10.9.2)

### ISSUE THREAD

**Issue by baraschi** [Shopify/dashing#408]
Hello!

I am running dashing on an ec2 ubuntu instance and the dashboard displays fine when I open Firefox or Chrome on a PC. 
When I try to open the dashboard on my MacBook, only the skeleton of the widgets appear and in the console, it says "Yeah! The dashboard has started! " but no data is received... until I stop the dashboard and then everything is displayed! 

Any ideas on how to fix this?

Thanks!

**Comment by tylermauthe** [comment]
Do you see data coming in from /events inside the Network Panel of Chrome?

It may be related to how Thin executes on this environment. The Event service is an SSE endpoint, so it is a bit weird -- the data keeps streaming out and the request never really finishes...

If there's no data coming in from the endpoint then the request is never actually leaving the server. There are many possible reasons for this...

If using Puma resolves this, that is one more reason that Dashing should make the switch from Thin.

**Comment by tylermauthe** [comment]
Please close this issue.
