### ISSUE TITLE
nvd3 support?

### ISSUE THREAD

**Issue by cakejelly** [Shopify/dashing#410]
Is it possible to add nvd3 support for adding custom graphs? Been trying to use this custom rickshawgraph widget (https://gist.github.com/jwalton/6614023) to assist but find myself constantly diving deep into the source to add functionality that nvd3 provides straight out of the box. Also, Rickshaw doesn't seem to support pie charts

**Comment by tylermauthe** [comment]
Please close this as it duplicates #192
