### ISSUE TITLE
Background image on dashboard

### ISSUE THREAD

**Issue by sethdippold21** [Shopify/dashing#416]
I'm not sure if this is possible, but is there a way to make the background of the whole dashboard an image and not one solid color?

**Comment by markymark292** [comment]
I am getting pretty good with Dashing and I have managed to add a background image quite easily, however, I have a dilemma.
I have two dashboards with different widgets. On one of them, I simply have a lot of "text" widgets displaying targets. I am trying to add a custom background to just some of those widgets, but not all. I have tried adding my own class in the scss file and binding it which I have included in the widget html file as normal and then added the data-backimage="backimage" hookup to the div in the erb file, however, I cannot see the image. 

Any help would be appreciated, even if it is to tell me it cannot be done, which I doubt! :-)

**Comment by zwergengott** [comment]
My background never shows if i try to use a local image file as my background - regardless of whether i use the absolute or relative path. It works perfectly if i use on online-url of an image, though. Has anyone an explanation for this problem?

**Comment by tylermauthe** [comment]
Serve the image from Dashing via HTTP. `file:// ` is flaky at best.

https://en.wikipedia.org/wiki/File_URI_scheme
