### ISSUE TITLE
Stop saving to history.yaml

### ISSUE THREAD

**Issue by gurmukhp** [Shopify/dashing#418]
Is there a way for a widget to not save data to the history.yaml file?

I have an event that fires an overlay. If I refresh the page, the overlay is shown immediately due to it existing in the history.yaml file.

Thanks!

**Comment by tylermauthe** [comment]
It is the job which injects data into the history.yml file and it is not possible to stop this from happening for a specific job. Furthermore, this is not a desirable feature.

I recommend increasing the frequency that your job sends events. If there are expensive operations that you perform in this job, you should decouple those actions from the scheduled task which sends the event. So you can have one scheduled task that runs every 5 minutes and stores data in memory and another scheduled task that runs every 5 seconds and shuttles out the data that is stored in memory.

**Comment by tylermauthe** [comment]
send_event also takes a third, mysterious parameter. If you set it to 'dashboard' the history.yml won't be written to.

It is witchcraft though, use at your peril.

Please close this issue.

**Comment by simzen85** [comment]
@tylermauthe I tried to use your suggested witchcraft but it doesn't work, is it updated ?

I really need this because right now our history.yml is very large and hence the whole dashboard is loading very slow (it seems to load the whole history.yml in memory)
