### ISSUE TITLE
Not seeing data in my widgets

### ISSUE THREAD

**Issue by aaroncole** [Shopify/dashing#422]
I set up Dashing on my Mac (Mavericks, Ruby 1.9.3) and am able to see the sample and sampletv dashboards, but there is no data in them.
![1080p-dashboard](https://cloud.githubusercontent.com/assets/465014/3861113/41e1faf2-1f2b-11e4-9481-a3dd611c233e.gif)

(I'm a front-end dev, so getting this far is pretty awesome for me)

What am I missing?

Update: 

When running 'dashing stop' I get this error:

/Users/aaroncole/.rvm/gems/ruby-1.9.3-p547/gems/thin-1.6.2/lib/thin/daemonizing.rb:129:in `send_signal': Can't stop process, no PID found in tmp/pids/thin.pid (Thin::PidFileNotFound)
	from /Users/aaroncole/.rvm/gems/ruby-1.9.3-p547/gems/thin-1.6.2/lib/thin/daemonizing.rb:111:in `kill'
	from /Users/aaroncole/.rvm/gems/ruby-1.9.3-p547/gems/thin-1.6.2/lib/thin/controllers/controller.rb:94:in `block in stop'
	from /Users/aaroncole/.rvm/gems/ruby-1.9.3-p547/gems/thin-1.6.2/lib/thin/controllers/controller.rb:135:in `tail_log'
	from /Users/aaroncole/.rvm/gems/ruby-1.9.3-p547/gems/thin-1.6.2/lib/thin/controllers/controller.rb:93:in `stop'
	from /Users/aaroncole/.rvm/gems/ruby-1.9.3-p547/gems/thin-1.6.2/lib/thin/runner.rb:199:in `run_command'
	from /Users/aaroncole/.rvm/gems/ruby-1.9.3-p547/gems/thin-1.6.2/lib/thin/runner.rb:155:in `run!'
	from /Users/aaroncole/.rvm/gems/ruby-1.9.3-p547/gems/thin-1.6.2/bin/thin:6:in `<top (required)>'
	from /Users/aaroncole/.rvm/gems/ruby-1.9.3-p547/bin/thin:23:in `load'
	from /Users/aaroncole/.rvm/gems/ruby-1.9.3-p547/bin/thin:23:in `<main>'
	from /Users/aaroncole/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `eval'
	from /Users/aaroncole/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `<main>'

**Comment by tylermauthe** [comment]
Please close this issue.
