### ISSUE TITLE
Blank Dashboard

### ISSUE THREAD

**Issue by alexandredubois** [Shopify/dashing#424]
Hello,

I installed Dashing on a windows machine (ruby 1.9.3) and after creating a new dashing project (dashing new project / bundle / dashing start) the content is not displayed... The localhost:3030/sample page is responding but i can only see the following on a dark gray background

    Try this: curl -d '{ "auth_token": "YOUR_AUTH_TOKEN", "text": "Hey, Look what I can do!" }' \http://localhost:3030/widgets/welcome

Analysing the source code of the HTML page, i notices that accessing http://localhost:3030/assets/application.js route, i see the following error message

    throw Error("ExecJS::RuntimeError: \n  (in D:/Tools/dashboard/dashboard_project/assets/javascripts/application.coffee)")

Any hints ?

Best regards,

Alex

**Comment by eddgrant** [comment]
Hi @cefigueiredo - I'm experiencing exactly the same issue as described here in a *nix environment. My setup is as follows:

* Ubuntu 14.04
* Ruby 1.9.3p3.8.5 (provided by local rbenv install)

Steps taken:
* Clone dashing git repo
* dashing new sweet_dashboard_project
* cd sweet_dashboard_project
* bundle
* dashing start

I see no errors in the console and exactly the same issue with the screen not displaying and the JS Exception being thrown.

Also tried with ruby-2.1.5 but with the same results.

Any help greatly appreciated as this has completely thrown a spanner in the works of us starting to play with dashing.

Cheers.

**Comment by eddgrant** [comment]
Gah - immediately after posting the above coment I found https://github.com/Shopify/dashing/issues/249#issuecomment-33990854 . I then installed ``NodeJS`` (using ``nvm``) and then used ``npm`` to install ``coffee-script`` and dashing now works. 

Could this be something to do with certain O/Ses (i.e. Mac) having coffee-script pre-installed and Windows/ *nix not? If this can be confirmed it would be great to update the instructions on http://shopify.github.com/dashing . I'd offer up a pull request but I can't find the source of this page on GitHub.

Cheers,

Edd

**Comment by cefigueiredo** [comment]
Great that you solved your problem! :D

The only relation I can see, is with the javascript engine, that when u install Node.js, you use its engine.
So just by installing node.js, you should use the `coffee-script` gem without problem, don't being necessary install it by `npm`. 

You could try install only the gem `therubyracer` besides node.js, to remove third-party dependencies.

**Comment by tylermauthe** [comment]
http://stackoverflow.com/questions/12520456/execjsruntimeerror-on-windows-trying-to-follow-rubytutorial

Go with option #3 in the accepted answer.
