### ISSUE TITLE
Monitoring from Solarwinds

### ISSUE THREAD

**Issue by around01** [Shopify/dashing#425]
We have most of our data coming into the Dashing software from Solarwinds using sql commands.  Is there a way to turn the icons all read if we can't get any data reply from the sql database for solarwinds?  This would be more from the outside of the application trying to verify we're up.  We had a network outage yesterday and all our dashing icon's stayed "green" because it couldn't pull any data because it was off the network..

**Comment by tylermauthe** [comment]
There really isn't enough information here to provide a solid answer.

That being said, the code that is querying the database is assuming that it will be successful. You must modify this code to handle exceptional cases, like network outages.

Any decent database interface library will provide this capability.

Please close this issue.

**Comment by around01** [comment]
We figured out how to complete this.  Thanks.. Closing the ticket

**Comment by sapg** [comment]
Any chance you could share your config?
