### ISSUE TITLE
Size of meter number

### ISSUE THREAD

**Issue by danilochilene** [Shopify/dashing#428]
How can I change the font size of meter number?

This is the piece of code I wanted to change:

<input style="width: 104px; height: 66px; position: absolute; vertical-align: middle; margin-top: 66px; margin-left: -152px; border: 0px none; background: none repeat scroll 0% 0% transparent; font: bold 40px Arial; text-align: center; color: rgb(255, 255, 255); padding: 0px;" readonly="readonly" data-fgcolor="rgb(255, 255, 255)" data-bgcolor="rgb(102, 43, 76)" data-min="0" data-max="100" class="meter" data-angleoffset="-125" data-anglearc="250" data-width="200" data-readonly="true" data-bind-value="value | shortenedNumber | prepend prefix | append suffix" data-bind-data-min="min" data-bind-data-max="max" font-size="30px">

I tried put font-size="30px" but it's using this  font: bold 40px Arial

**Comment by ggrilli75** [comment]
1- you must abir file: your dashboard / assets / stylesheets / application.scss

2 - Look for the following entry:
      .**widget {
                     text-align: center;
                     width: inherit;
                     height: inherit;
            
                    display: table-cell;
                    vertical-align: middle;
}**
  and adds the corresponding font-size line _(eg font-size: 20px;_)

3 - Save this file

4 - Open the corresponding file .scss meter-widgets (/ your dashboard / widgets / meter

5 - Go to the entrance
      
        **input.meter {
                             background-color: $ meter-background;
                             Color: #fff;                          
                             }**

and adds the size for your font, in my case _font-size: 35px;_

6 - Save and go!
