### ISSUE TITLE
data-bind-style CSS transformations?

### ISSUE THREAD

**Issue by ppenpraze** [Shopify/dashing#429]
Hi, I'm having some problems getting CSS transformations working with bindings. Other CSS style properties like background color work fine though. Changing the class is not sufficient since I have use dynamic values. Is this kind usage supported? 

I've tried using both CSS style and CamelCase versions, but with no luck:

 "MozTransform : rotate(180.0deg)" or "-moz-transform : rotate(180.0deg)"

Inside the widget HTML I'm using:
data-bind-style="dailygoalgaugeright"

As a workaround, I can set it via CoffeeScript in the widget, but would like to do everything in CSS and HTML using Batman bindings.

**Comment by tylermauthe** [comment]
Batman has a style binding for this: data-style-#{styleAttrName}

However I don't think it supports vendor specific prefixes at this time.

You may have success with a custom widget -- I don't think it would be difficult. The approach I would take would be to attach to the onData method and use jQuery to apply the transformation from the data value.

**Comment by tylermauthe** [comment]
Please close this issue.
