### ISSUE TITLE
Clickable (parts of) widgets with dynamic URLs

### ISSUE THREAD

**Issue by Rolfie** [Shopify/dashing#431]
I would like to have a widget which is clickable (and does not follow the link when being dragged) and the target url should be set dynamically. It should be able to define multiple links within one widget.

For example, when I have a RSS feed with multiple items being displayed as a list, I want to be able to click a single item which should open the full url to that article. It could also be the case that I would have a widget with only one item (with title and description) and want for example to be able to click the title and have the full article being opened. Preferable this would be an option to enable/disable on a widget by widget base and not based on the actual type of the widget.

I feel bad for opening a issue as I hope this should hopefully be possible, but which I couldn't figure out so far. Issues #36 and #76 seem related but this a) Only involves the whole widget and b) It is only a static URL.

Any help would be appreciated!

**Comment by tylermauthe** [comment]
The drag & drop functionality is provided by Gridster.js - the docs for that library may be useful.

You can probably just do what is recommended here: https://github.com/ducksboard/gridster.js/issues/58

So something like this inside your widget file:
```coffeescript
$(@node).data('gridster').disable()
```

**Comment by tylermauthe** [comment]
You can do this with CSS too: https://github.com/ducksboard/gridster.js/issues/195

Adding .no-drag to an element would disable dragging.

```css
.no-drag .gs-resize-handle-both{
  display:none;
}
```
