### ISSUE TITLE
Widgets to change values based on selection ?

### ISSUE THREAD

**Issue by nandaceg007** [Shopify/dashing#436]
Do we have a feature where the dashboard shows different values based on a selection ?
As in, assume we have a dashboard with a set of widgets along with a selector(drop-down sort of). As the value changes in the selector, the values of the widgets changes as well. 

Is this achievable with the current framework ? If not, are there any workarounds ?

**Comment by tylermauthe** [comment]
Dashing supports posting arbitrary data via HTTP POST. This is protected by an auth token, specified within your config.ru. Finally, Dashing is really just a collection of open source tools and at it's core it's really a Sinatra app.

Armed with this knowledge, you have several options. The simplest is using an AJAX POST request:
```
$.post "/widgets/myWidget", "{ \"auth_token\": \"YOUR_AUTH_TOKEN\", \"value\": #{value} }"
```

This had the distinct disadvantage of exposing the keys to your kingdom on the client side. A better approach would be to perform this post on the server side, thus hiding the auth token. You can expose this server-side post request as a Sinatra route and then post data to the route you define instead.
