### ISSUE TITLE
Expandable Widgets

### ISSUE THREAD

**Issue by pcavalheiro** [Shopify/dashing#441]
Hello,

It's possible to make  expandable widgets in dashing framework like that : http://gridster.net/demos/expandable-widgets.html

How can i use resize_widget method of gridster.js in dashing?

**Comment by tylermauthe** [comment]
You can pull out the gridster instance of a widget like this:
```
gridster = $(@node).parents('ul').data('gridster')
```

From there you can resize it with the resize_widget method:
```
gridster.resize_widget(1, getRandomInt(1, 4), getRandomInt(1, 4))
```
