### ISSUE TITLE
scss changes not showing up in widget

### ISSUE THREAD

**Issue by Sweenj** [Shopify/dashing#444]
I'm trying to change some of the colors the scss file uses and enlarge the text of the legend. I've edited these values in the rickshawgraph.scss file, but it remains unchanged when I launch the dashing rickshaw graph.  I've changed the background color in the .erb file but for the sass declaration colors it is declared in the scss file.

https://gist.github.com/jwalton/6614023 

Here is my block of edits.
// ----------------------------------------------------------------------------
// Sass declarations
// ----------------------------------------------------------------------------
$background-color:  #dc5945;

$title-color:       rgba(126, 126, 126, 0.7);
$moreinfo-color:    rgba(126, 126, 126, 0.5);
$tick-color:        rgba(0, 0, 0, 0.4);

Here is the block from the original file.
// ----------------------------------------------------------------------------
// Sass declarations
// ----------------------------------------------------------------------------
$background-color:  #dc5945;

$title-color:       rgba(255, 255, 255, 0.7);
$moreinfo-color:    rgba(255, 255, 255, 0.5);
$tick-color:        rgba(0, 0, 0, 0.4);

Any help would be appreciated.  Has anyone had a similar problem?  
![image](https://cloud.githubusercontent.com/assets/8270787/4304927/fa5fe676-3e74-11e4-9f1b-cb87e3e88d1c.png)

**Comment by tylermauthe** [comment]
Have you tried https://gist.github.com/jwalton/6614023#supported-html-data-fields ?

It looks like there are a lot of colour configuration options in there.

You have changed the colour of the Title of the widget and the colour of the More Info caption -- neither of these are shown in the attached image. What are you trying to change the colour of specifically?

The text in the legend can be enlarged by adjusting this value: https://gist.github.com/jwalton/6614023#file-rickshawgraph-scss-L76

Please close this issue if you've already solved it.

**Comment by Sweenj** [comment]
Thanks Tyler, I was able to solve the issue, I'll post my code shortly.

**Comment by tylermauthe** [comment]
Thanks, that would be great as these issues can act as a knowledge base for others :+1:
