### ISSUE TITLE
rickshaw hover property

### ISSUE THREAD

**Issue by mskaraca** [Shopify/dashing#447]
Hi,

 I was not able to implement hover feature in dashing rickshaw graph

here (https://gist.github.com/jwalton/6614023) in the comments section, a way was proposed but not it does not work

Any help..?

**Comment by tylermauthe** [comment]
I just implemented this last night, I reverse engineered this example: http://code.shutterstock.com/rickshaw/examples/lines.html

There were two key insights:
- There is a ton of CSS that you need to copy over
- call `new Rickshaw.Graph.HoverDetail` with your `@graph` before the first `@graph.render()`

Let me know how it goes!
