### ISSUE TITLE
Add a <hr> tag on List widget

### ISSUE THREAD

**Issue by bicofino** [Shopify/dashing#450]
It's possible on List widget add a <hr> tag between values?

Example:
label: test , value: 0
label: test1 , value: 1
<hr> 
label: test2 , value: 2

**Comment by tylermauthe** [comment]
Perhaps css fits the bill?

```
  li {
    border-top: 3px solid #ccc;
  }
  li:first-child {
    border-top: none;
  }
```

**Comment by tylermauthe** [comment]
Please close this issue.
