### ISSUE TITLE
Adding widgets to dashboard while running

### ISSUE THREAD

**Issue by martenpalsson** [Shopify/dashing#451]
Hi,
I would like to emulate the behavior of fitbit.com where they allow the user to add more widgets to their dashboard from a side menu. How is this done, i.e how can I add and remove widgets from the dashboard while it is running? I found some information in issue #313 but he is not really after what I am. 

I am pretty new to dashing so any help with examples or just tips on approaches are very welcome.

**Comment by tylermauthe** [comment]
Why do you want this? I don't think Dashing is really suited to your use case.

It is meant for people who like to write code.

**Comment by tylermauthe** [comment]
Dynamic management of Dashboards is way outside the scope of Dashing.

Sounds like one of the paid Dashboard services might be better for you:
https://github.com/Shopify/dashing/wiki#why-use-dashing-when-there-are-plenty-of-cloud-based-dashboards-out-there

**Comment by tylermauthe** [comment]
Also @kaltinril's suggestion will not work unless you add some kind of persistence layer...

**Comment by kaltinril** [comment]
Not sure what you mean @tylermauthe .  I did exactly as I stated and I've written code that dynamically builds up the dashboard based on comma delimited text files that are parsed.  Each one is assumed to be a widget, and the type and contents are inside the file.  This works great for us.

I'm not sure what you mean by Persistence layer?

**Comment by tylermauthe** [comment]
The comma delimited text file is persistence.

As I understand it, @martenpalsson wants to configure the dashboard inside Dashing (not through some CSV file). To do this, the changes made in the browser would have to be written back to the text file (or a database, or some other persistence layer). If they weren't, all changes made in the browser would be lost upon refresh.

Not sure why you'd prefer to create your dashboards as CSV's instead of HAML / ERB templates... Unless the CSV file is generated by some Hipster Batch or otherwise Dynamic process...

**Comment by kaltinril** [comment]
Ah gotcha thanks @tylermauthe , that makes sense.  I must have missed that part of the original request :)

We wanted a way to be able to "fire and forget", and not require development of the dashboard whenever we wanted a new widget to be displayed.

So we wrote code to dynamically build up the erb file, based on the contents of files in a directory.  (I will have to look into HAML/ERB).  The files can be dropped by anything (manually, via automation tools external to dashing, etc.  This means that dashing has no fingers or permissions into databases, applications, processes etc.

Our automation tool generates files everytime specific automations run.  The file contains the details for the widget, along with the data.

The rb file parses the files and creates the .erb file.

Again, this is just what worked well for us so we could setup Dashing, and never touch it again.

**Comment by tylermauthe** [comment]
Awesome, you are using a [Hipster Batch](http://www.thoughtworks.com/radar/techniques/hipster-batch) :+1:

**Comment by tylermauthe** [comment]
Please close this issue.

**Comment by PeterBi87** [comment]
I guess i have nearly the same question:
I would like to let the user add/remove widgets inside his/her personal dashboard. This process should be possible without touching code. Are there any pre-made dashings on github, where this is realized?

@kaltinril I guess your solution comes very close to my requirements. Is it possible to load it up? That would be really great.

I addition to that, i am open for every kind of ideas to make that possible.
