### ISSUE TITLE
Multiple meter graph in same widget

### ISSUE THREAD

**Issue by AntoninHL** [Shopify/dashing#452]
Hi,

I need to add another meter graph in the same widget.
I try many things, but impossible to have good result.

For example, if I try this:

class Dashing.Mmeter extends Dashing.Widget

  @accessor 'value1', Dashing.AnimatedValue
  @accessor 'value2', Dashing.AnimatedValue

  constructor: ->
    super
    @observe 'value1', (value1) ->
      $(@node).find(".mmeter").val(value1).trigger('change')

```
@observe 'value2', (value2) ->
  $(@node).find(".mmeter").val(value2).trigger('change')
```

  ready: ->
    mmeter = $(@node).find(".mmeter")
    mmeter.attr("data-bgcolor",mmeter.css("background-color"))
    mmeter.attr("data-fgcolor", mmeter.css("color"))
    mmeter.knob()

I have 2 meter graphs, but empty.... and sometimes, values are the same...

Thanks for help.

A.

**Comment by Hackuracy** [comment]
Hi,
did you solved your problem?
