### ISSUE TITLE
Highchart Funnel - non-commercial use

### ISSUE THREAD

**Issue by bstephenf** [Shopify/dashing#455]
Can anyone share code for how to implement a funnel chart. I see that it is one of the chart types available from highcharts but my attempt to implement was not successful.  If anyone has any code/experience (or an alternative to highcharts) to share, that would be great. :)

**Comment by tylermauthe** [comment]
Dashing comes with a Graph widget that is built with Rickshaw; however Rickshaw doesn't support funnel charts.

If you need this functionality, you will have to create it yourself. However, I recommend looking at how the Graph widget was implemented for an example of how you might do it yourself. Personally, I would copy the Graph widget and hack it up until it worked (and then clean it up for contribution!).

**Comment by tylermauthe** [comment]
With Highchart's license it doesn't really make sense for someone to create an Open-Sourced widget based on their libraries. Also, you can use Rickshaw's stacked bar graph to show the same data.

This issue can probably be closed.
