### ISSUE TITLE
Blinking widgets

### ISSUE THREAD

**Issue by doertedev** [Shopify/dashing#456]
https://github.com/Shopify/dashing/blob/master/templates/project/assets/stylesheets/application.scss#L156 I might have lost the oversight but what was the thought behind the blinking of the widgets? This just drove me nuts running dashing on a raspi for > 10mins...

**Comment by tylermauthe** [comment]
This is intended for the Number widget. A `status` field can be added to the event data which can be used as a visual indicator of an important metric.

If you are annoyed by this feature, I suggest that you do not use it. The template dashboard does not implement this functionality.

This issue can be closed.
