### ISSUE TITLE
Layout is messed up and getting js errors on ubuntu - worked fine first time on osx

### ISSUE THREAD

**Issue by jacksonofalltrades** [Shopify/dashing#459]
You can see the problems here.

http://54.183.101.138:3030/ec-builds

I cannot for the life of me figure out what went wrong. I checked in my code, pulled it on an ubuntu machine, and it's all messed up when I run it here.

Any help would be greatly appreciated.

**Comment by tylermauthe** [comment]
Issue can be closed.
