### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by GunnarLindholm** [Shopify/dashing#461]
As a regular user I'm trying to install dashing but I get
$ gem install dashing
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /var/lib/gems

What should I do?

**Comment by tylermauthe** [comment]
This is an issue with your Ruby environment configuration (not Dashing). Are you able to install other gems?

I recommend using RVM or rbenv to manage this configuration for you...

http://cbednarski.com/articles/installing-ruby/

Alternatively, you can hack up your Ubuntu environment until this works. Yuck...

**Comment by tylermauthe** [comment]
Please close this issue.
