### ISSUE TITLE
Showing dashboard application version in a text widget

### ISSUE THREAD

**Issue by tooh** [Shopify/dashing#462]
I want to show the dashboard application version in a text widget.
I use git tags and found following code

http://www.kudelabs.com/2011/12/22/tags-in-git-for-sane-version-numbers

``` ruby  
# VERSIONING
git_version_cmd = "git describe"
$revision = `#{git_version_cmd}`
$revision = $revision.strip
puts "starting version: #{$revision}"
```

This code is working OK on its own.
Recommendation was to put this in a git_helper.rb file.

What is the best place to implement this in Dashing ?

Peter

**Comment by tylermauthe** [comment]
Alternatively, you can add it as a helper as recommended.

This is done in your config.ru... See the [example dashboard template](https://github.com/Shopify/dashing/blob/6c6d71cee1056be596af40921761eeebee368828/templates/project/config.ru#L6-L11) if you've removed this section from your dashboard.
