### ISSUE TITLE
Long loading times for /events 

### ISSUE THREAD

**Issue by kevster** [Shopify/dashing#463]
Hi,

my Dashing setup is running pretty smoothly, except /events is taking very long to load:

127.0.0.1 - - [13/Oct/2014 11:13:39] "GET /events HTTP/1.1" 200 - 60.3124
127.0.0.1 - - [13/Oct/2014 11:13:58] "GET /teamA HTTP/1.1" 200 7770 0.0668
127.0.0.1 - - [13/Oct/2014 11:13:58] "GET /events HTTP/1.1" 200 - 15.5109
127.0.0.1 - - [13/Oct/2014 11:14:01] "GET /views/campaign.html HTTP/1.1" 200 824 0.0010
127.0.0.1 - - [13/Oct/2014 11:14:01] "GET /views/twitter_list.html HTTP/1.1" 200 1633 0.0008
127.0.0.1 - - [13/Oct/2014 11:14:01] "GET /views/instagram.html HTTP/1.1" 200 1796 0.0008
127.0.0.1 - - [13/Oct/2014 11:14:01] "GET /views/facebook_group.html HTTP/1.1" 200 1728 0.0009
127.0.0.1 - - [13/Oct/2014 11:14:01] "GET /views/map.html HTTP/1.1" 200 611 0.0007
127.0.0.1 - - [13/Oct/2014 11:14:01] "GET /views/iframe.html HTTP/1.1" 200 671 0.0012
127.0.0.1 - - [13/Oct/2014 11:14:01] "GET /null HTTP/1.1" 304 - 0.0010
127.0.0.1 - - [13/Oct/2014 11:14:01] "GET /views/contact.html HTTP/1.1" 200 571 0.0012
127.0.0.1 - - [13/Oct/2014 11:14:31] "GET /events HTTP/1.1" 200 - 30.0936

127.0.0.1 - - [13/Oct/2014 11:18:20] "GET /events HTTP/1.1" 200 - 60.2345
127.0.0.1 - - [13/Oct/2014 11:18:53] "GET /events HTTP/1.1" 200 - 30.1529
127.0.0.1 - - [13/Oct/2014 11:19:26] "GET /events HTTP/1.1" 200 - 30.1497
127.0.0.1 - - [13/Oct/2014 11:19:59] "GET /events HTTP/1.1" 200 - 30.1549

Which causes the dashboard to sometimes think it's lost the connection:

2014-10-13 11:50:00.411Connection opened Event {clipboardData: undefined, path: NodeList[0], cancelBubble: false, returnValue: true, srcElement: EventSource…} application.js:15007
2014-10-13 11:50:30.541Connection error Event {clipboardData: undefined, path: NodeList[0], cancelBubble: false, returnValue: true, srcElement: EventSource…} application.js:15011
2014-10-13 11:50:33.613Connection opened Event {clipboardData: undefined, path: NodeList[0], cancelBubble: false, returnValue: true, srcElement: EventSource…} application.js:15007
2014-10-13 11:51:03.790Connection error Event {clipboardData: undefined, path: NodeList[0], cancelBubble: false, returnValue: true, srcElement: EventSource…} 

I know that it's possible to increase the threshold to 90 seconds according to https://github.com/Shopify/dashing/issues/113 but it just seems wrong that a page should take 30-60 seconds to load, especially when dealing with very light data. Does anyone have any idea why /events might take so long to load?

**Comment by tylermauthe** [comment]
Not sure if you're aware, but `/events` is an SSE endpoint - it streams as long as the browser will let it.

Try loading it up in a browser, you will see that as each job runs more data is added to the page... Eventually it might timeout - this is a limitation of the browser mainly. This issue can mostly be skirted by increasing the frequency that events are sent.

More info about SSE's: http://en.wikipedia.org/wiki/Server-sent_events

Other than /events taking so long to load, what other problems are you seeing? Widgets not updating? Initial Dashboard load time is slow? etc?

I think you might have better luck diagnosing this issue using your browser's network panel than by looking at the server logs -- just a hunch though!

**Comment by tylermauthe** [comment]
Please close this ticket.
