### ISSUE TITLE
Starting Dashing as a Windows Service

### ISSUE THREAD

**Issue by kaltinril** [Shopify/dashing#465]
Can dashing be started as a windows service in some manner other than using a batch file, cmd.exe and srvany?

I don't want to remain logged in just to keep the cmd.exe window open for dashing to be open.

**Comment by tylermauthe** [comment]
Dashing requires an execjs compatible JavaScript engine:
https://github.com/sstephenson/execjs

On Windows, that should be built in (JScript):
http://msdn.microsoft.com/en-us/library/9bbdkx3k.aspx

Maybe that is an avenue to explore... Is JScript available to ruby to use.

**Comment by patdowney** [comment]
Depending on what widgets you're using I'd also look at the golang port of dashing, I've got an example here where i've added some windows support to an example (created by @gigablah): https://github.com/patdowney/windows-dashing-go-demo - if you build it on windows the exe that is output can be installed as a service using `sc.exe`.

**Comment by tylermauthe** [comment]
https://github.com/gsmedley/thin_service - Use this.

**Comment by pushmatrix** [comment]
Closing this for now. Re-open if you are still having issues.
