### ISSUE TITLE
Periodically deleting thin.log 

### ISSUE THREAD

**Issue by baraschi** [Shopify/dashing#469]
Hello!
I'm running dashing on an AWS EC2 Ubuntu instance.
I run it in the background (dashing start -d) so that I don't have to be connected to the instance at all times.
My problem is that the thin.log file keeps on getting larger and larger and takes up all the space of my instance. When this happens, I don't even have enough space to run dashing.
Does anyone know how to periodically delete  the thin.log file (or not have it at all?)
Thank you!

**Comment by tylermauthe** [comment]
You could also look at running dashing via thin and telling it not to log anything.

This has the distinct disadvantage of being impossible to determine what went wrong if things go sideways.

Just roll your logs with cron as @derwin12 suggests.

**Comment by tylermauthe** [comment]
This is not a Dashing issue. Please close.
