### ISSUE TITLE
scroll inside widgets not working

### ISSUE THREAD

**Issue by cjdcordeiro** [Shopify/dashing#471]
Hi,

I am pushing a big list of values into a list widget, but it is not scrolling automatically and I guess it should be supposed to by looking at the gridster code no?

I am getting a huge widget which ends up overlapping others.

Any idea how to solve this?
Thanks

**Comment by tylermauthe** [comment]
You can adjust the widgets data-sizex or data-sizey parameters in your dashboard.erb file...

```
<li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
```
replaced with:
```
<li data-row="1" data-col="1" data-sizex="4" data-sizey="4">
```
