### ISSUE TITLE
Send Event - current & last values

### ISSUE THREAD

**Issue by howardsternisbatman** [Shopify/dashing#472]
Hello

What would the correct syntax be to send current and last values to the valuation/number widget? I can curl it with the following.

curl -d '{ "auth_token": "YOUR_AUTH_TOKEN", "last": 0, "current": 10 }' \http://localhost:3030/widgets/valuation

thanks for your help.

**Comment by tylermauthe** [comment]
From ruby?
```
send_event( "valuation", { last: 0, current: 10 } )
```
