### ISSUE TITLE
Run dashing behind proxy

### ISSUE THREAD

**Issue by lukebo** [Shopify/dashing#474]
Hi,

I need to run the dashing server behind a proxy, so that all the ruby scripts in /jobs obtain their data from the internet through through that proxy. I set the http_proxy systemvariable in /etc/environment successfully but ruby does not seem to use it. Instead I foud some fancy code how to tell NET:HTTP to use a proxy. Unfortunately as my ruby experience is VERY limited (approaching zero) I am too stupid to implement this and there are lots of scripts in my jobs folder.... Is it really true, that i need to change that in every script or am i missing some trick? I would save lots of time if there would be a simple way to tell ruby to use $http_proxy globally.......

Best regards

Luke

**Comment by tylermauthe** [comment]
http://stackoverflow.com/questions/6868507/automatically-adding-proxy-to-all-http-connections-in-ruby

This is not a Dashing issue... Please close.
