### ISSUE TITLE
JSON Get Request not being properly accepted from Icinga

### ISSUE THREAD

**Issue by brockoffdev** [Shopify/dashing#480]
Hello, relative newbie here...

I have been working to fix an unfortunate issue where my HTTP Get from Icinga is not properly bringing back the JSON it is calling. The "icinga_status" json group is coming down fine, however when the get request reaches the JSON array of "status" => "service_status"/"host_status", the content no longer renders properly:
```
"status": {
"service_status": [

]
}
}
```
I have verified the actual URL works to pull the JSON via both HTTParty and via Chrome, but something is blocking it on either the Thin/Rails side of things. I know that the gems are not an issue, however, as I have other instances of JSON being brought down properly.

For the record, I am utilizing this really great icinga plugin: [lazyfrosch/dashing-icinga](https://github.com/lazyfrosch/dashing-icinga)

Thanks!

**Comment by tylermauthe** [comment]
This is not a Dashing issue.

Please close this, as per [this comment](https://github.com/lazyfrosch/dashing-icinga/issues/1#issuecomment-64153012).
