### ISSUE TITLE
Possible to send more than one data value to the number widget?

### ISSUE THREAD

**Issue by howardsternisbatman** [Shopify/dashing#481]
I'd like to be able to show a customer satisfaction score (done), and also show how many surveys were returned.

The Number widget is displaying the csat score nicely but I am puzzled on how to pass the number to display the survey count on the same numbers widget.  

Any pointers would be appreciated.

excel.rb  snip

s = Roo::Excel.new("/home/administrator/manchvegas/xls/newcases.xls")
send_event('agentcsatmonth', {current: s.cell('H',30)})

s = Roo::Excel.new("/home/administrator/manchvegas/xls/newcases.xls")
send_event('agentsurvey', {current: s.cell('G',30)})

.erb snippet

		<li data-row="2" data-col="1" data-sizex="1" data-sizey="1">
  div data-id="agentcsatmonth" data-view="Number" data-title="agent CSAT MTD" style="background-color: #B06B0B" data-prefix="" data-suffix="%"></div>
    i class="icon-thumbs-up  icon-background"></i>

**Comment by tylermauthe** [comment]
You could make the number widget alternate between two different numbers (changing the title also to reflect the current mode). This could be accomplished by two separate offset Rufus jobs on the backend, though this approach may get strange with certain values:

```
SCHEDULER.every '60s', :first_in => 0 do
   # First Value
   send_event('number',{title:'First Number', current: 2})
end
SCHEDULER.every '60s', :first_in => '30s' do
   # Second Value -- Offset
   send_event('number',{title:'Second Number', current: 1})
end
```

Another approach for alternating values would be to use a mutex, you can see more about that on the Rufus docs: https://github.com/jmettraux/rufus-scheduler

If you don't want to alternate between numbers, you might have success by using a data-foreach-#{itemName}. You can read more about how to do this in the Batman docs: http://batmanjs.org/docs/api/batman.view_bindings.html#data-foreach

If you do take the approach of using data-foreach and find you want to show more data or start to customise in other ways, you should look into creating your own custom widgets. There are lots of great examples here: https://github.com/Shopify/dashing/wiki/Additional-Widgets

Good luck and let me know if you have any more questions.
