### ISSUE TITLE
Rickshaw Axis cropped

### ISSUE THREAD

**Issue by felipefontoura** [Shopify/dashing#484]
Hello Folks!

I already tryed to adjust the axis padding from my graphs but It insists to being cropped at borders. I adjusted CSS and tryed to change the JS, but nothing... Check I'd like to fix:

![graph1](https://cloud.githubusercontent.com/assets/281622/5234540/8cf724c0-77b6-11e4-9394-62a9cb11d267.png)
![graph2](https://cloud.githubusercontent.com/assets/281622/5234541/8d0a5de2-77b6-11e4-9edf-abe0f41a215f.png)

As you can seed the X and Y axis was cropped.

Thanks to much for Dashing... It's help us a lot!

**Comment by tylermauthe** [comment]
How are you using the padding attribute? I think that is the correct approach to solving it.

This solved it for me: http://stackoverflow.com/questions/21708577/rickshaw-graph-max-y-axis-is-cutoff

**Comment by felipefontoura** [comment]
Thanks! @tylermauthe I'll check and give a feedback here.

**Comment by felipefontoura** [comment]
Problem fixed! :+1: Thanks!
