### ISSUE TITLE
displaying widget with in a widget

### ISSUE THREAD

**Issue by 7sense** [Shopify/dashing#487]
Hi,

I will try to explain the issue as clear as I can.

Basically, I have widget A (created based on Text) which is reading server status (up / down) and change the background.

Because we have many services, for each service we have multiple servers. We need to check a few web page for on each server for each service.

That is to say, I had to create a widget B in which I used javascript to generate a table, and for each cell (td), I added a widget A.

e.g.
< table>
< tr>
< td class="className" data-id="id1", data-view="A", data-title=""></td>
< td class="className" data-id="id2", data-view="A", data-title=""></td>
< td class="className" data-id="id3", data-view="A", data-title=""></td>
......
< /tr>
< /table>

If I hard code above table in widget B, it works fine when I send data to each id of widget A. However, If I use javascript to generate the table, data cannot be passed to widget A.
......
var td = document.createElement("td");
td.setAttribute("class", "className");
td.setAttribute("data-id", idNumber);
td.setAttribute("data-view", "A");
td.setAttribute("data-title", "");
......

It seems that the "data-view" attribute was not recognised as a Widget.

Hope this make sense. You advice is much appreciated!

Cheers,
Kevin

**Comment by tylermauthe** [comment]
That is a lot of servers! I would probably create a custom widget for this...

I would move those getJSON calls to the back end into a Rufus job (or two...) and do as @rmosolgo suggested -- using the `data-foreach-#{item_name}` Batman binding.

Read more about Batman bindings here: http://batmanjs.org/docs/api/batman.view_bindings.html

There are many examples of it's use in the widgets folder of a Dashing app and there are lots of excellent widgets here: https://github.com/Shopify/dashing/wiki/Additional-Widgets
