### ISSUE TITLE
Expanding dashboard-level actions

### ISSUE THREAD

**Issue by xamroc** [Shopify/dashing#489]
So far dashboard-level actions only has 'reload'. I have

```
#=required dashing.js
```

on my `application.coffee` but the actual file is not in my application directory. I assume it's linking to [this file](https://github.com/Shopify/dashing/blob/6c6d71cee1056be596af40921761eeebee368828/javascripts/dashing.coffee) and actions referring to this portion:

```
class window.Dashing extends Batman.App
  @on 'reload', (data) ->
    window.location.reload(true)

  @root ->
Dashing.params = Batman.URI.paramsFromQuery(window.location.search.slice(1));
```
 If I wanted to expand its actions, how should I do so?

I tried creating `dashing-cus.coffee` under `assets/javascripts` but I can't figure out how to extend from here. My code below is breaks my dashboard and gives me `Uncaught TypeError: Cannot read property 'prototype' of undefined` error:

**dashing-cus.coffee**
```
#= require jquery
#= require es5-shim
#= require batman
#= require batman.jquery

class window.Dashing extends Batman.App
  @on 'alert', (data) ->
    alert data
```

**Comment by tylermauthe** [comment]
You can achieve this without reaching into poor Dashing's brain like that.

Inside your application.coffee:
```
Dashing.on 'alert', ->
  alert("Woot!")
```
Test it out in bash:
```
$ curl -i -d '{"auth_token": "AUTH_TOKEN", "event": "alert"}' http://localhost:3030/dashboards/myDashboard
