### ISSUE TITLE
Is it possible to run Dashing Dashboard ruby app in IDEs like Ruby Mine?

### ISSUE THREAD

**Issue by uheroku** [Shopify/dashing#491]

**Comment by tylermauthe** [comment]
This question is incredibly vague... I will answer in kind: yes.

**Comment by tylermauthe** [comment]
It has sinatra support -- everything else should be dependant on your environment configuration. So as long as Dashing runs normally for you, it should run from Ruby Mine.

http://blog.jetbrains.com/ruby/2012/06/rubymine-nire-eap-welcome-sinatra/
