### ISSUE TITLE
Dashing installed but giving Javascript runtime error

### ISSUE THREAD

**Issue by walterObrien** [Shopify/dashing#492]
[root@Scorpion ~]# cd /sweet_dashboard_project
-bash: cd: /sweet_dashboard_project: No such file or directory
[root@Scorpion ~]# cd sweet_dashboard_project
[root@Scorpion sweet_dashboard_project]# bundle
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Installing addressable 2.3.6
Using backports 3.6.4
Installing buftok 0.2.0
Using coffee-script-source 1.8.0
Using execjs 2.0.2
Using coffee-script 2.2.0
Using daemons 1.1.9
Using rack 1.5.2
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using rufus-scheduler 2.0.24
Using sass 3.2.19
Using rack-protection 1.5.3
Using tilt 1.4.1
Using sinatra 1.4.5
Using multi_json 1.10.1
Using rack-test 0.6.2
Using sinatra-contrib 1.4.2
Using hike 1.2.3
Using sprockets 2.10.2
Using eventmachine 1.0.3
Using thin 1.6.3
Using thor 0.18.1
Using dashing 1.3.4
Installing equalizer 0.0.9
Installing multipart-post 2.0.0
Installing faraday 0.9.0
Installing http_parser.rb 0.6.0
Installing http 0.6.3
Installing json 1.8.1
Installing memoizable 0.4.2
Installing naught 1.0.0
Installing simple_oauth 0.3.0
Installing twitter 5.13.0
Using bundler 1.7.6
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
[root@Scorpion sweet_dashboard_project]# dashing start
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/execjs-2.0.2/lib/execjs/runtimes.rb:51:in `autodetect': Could not find a JavaScript runtime. See https://github.com/sst                                                                                                                                                             ephenson/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/execjs-2.0.2/lib/execjs.rb:5:in `<module:ExecJS>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/execjs-2.0.2/lib/execjs.rb:4:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/backports-3.6.4/lib/backpo                                                                                                                                                             rts/std_lib.rb:9:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/backports-3.6.4/lib/backpo                                                                                                                                                             rts/std_lib.rb:9:in `require_with_backports'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/coffee-script-2.2.0/lib/co                                                                                                                                                             ffee_script.rb:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/backports-3.6.4/lib/backpo                                                                                                                                                             rts/std_lib.rb:9:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/backports-3.6.4/lib/backpo                                                                                                                                                             rts/std_lib.rb:9:in `require_with_backports'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/coffee-script-2.2.0/lib/co                                                                                                                                                             ffee-script.rb:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/backports-3.6.4/lib/backpo                                                                                                                                                             rts/std_lib.rb:9:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/backports-3.6.4/lib/backpo                                                                                                                                                             rts/std_lib.rb:9:in `require_with_backports'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dashing-1.3.4/lib/dashing/                                                                                                                                                             app.rb:5:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dashing-1.3.4/lib/dashing.                                                                                                                                                             rb:3:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dashing-1.3.4/lib/dashing.                                                                                                                                                             rb:3:in `<top (required)>'
        from config.ru:1:in `require'
        from config.ru:1:in `block in <main>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/builde                                                                                                                                                             r.rb:55:in `instance_eval'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/builde                                                                                                                                                             r.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.3/lib/rack/adapte                                                                                                                                                             r/loader.rb:33:in `eval'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.3/lib/rack/adapte                                                                                                                                                             r/loader.rb:33:in `load'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.3/lib/thin/contro                                                                                                                                                             llers/controller.rb:182:in `load_rackup_config'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.3/lib/thin/contro                                                                                                                                                             llers/controller.rb:72:in `start'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.3/lib/thin/runner                                                                                                                                                             .rb:200:in `run_command'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.3/lib/thin/runner                                                                                                                                                             .rb:156:in `run!'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.3/bin/thin:6:in `                                                                                                                                                             <top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/thin:23:in `load'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/thin:23:in `<main>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in                                                                                                                                                              `eval'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in                                                                                                                                                              `<main>'
[root@Scorpion sweet_dashboard_project]#

**Comment by tylermauthe** [comment]
It appears you are on Linux, add therubyracer to your gemfile:

```
# Linux only Gems
if RUBY_PLATFORM =~ /x86_64-linux/
	gem 'therubyracer'
end
```
