### ISSUE TITLE
Is it possible to deploy Dashing Dashboard in Amazon AWS with oci8 (oracle) connections?

### ISSUE THREAD

**Issue by uheroku** [Shopify/dashing#493]

**Comment by tylermauthe** [comment]
You can deploy Dashing to any system with Ruby 1.9+... So yes, it can be deployed to AWS.

Here is a rubygem for handling oci8:
https://github.com/kubo/ruby-oci8

Dashing is a general library that allows you to display data from any system that ruby can get its hands on. The backend is just a set of jobs that run at intervals and execute ruby code. The front-end is an awesome widget-based system built on top of batman.js.
