### ISSUE TITLE
Getting these Error while deploy it in Heroku

### ISSUE THREAD

**Issue by uheroku** [Shopify/dashing#494]
-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-1.9.3
###### WARNING:
       Removing `Gemfile.lock` because it was generated on Windows.
       Bundler will do a full resolve so native gems are handled properly.
       This may result in unexpected gem versions being used in your app.
       In rare occasions Bundler may not be able to resolve your dependencies at all.
       https://devcenter.heroku.com/articles/bundler-windows-gemfile

-----> Installing dependencies using 1.6.3
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4
       Fetching gem metadata from https://rubygems.org/...........
       Resolving dependencies...
       Installing buftok 0.2.0
       Installing addressable 2.3.6
       Installing coffee-script-source 1.8.0
       Installing execjs 2.0.2
       Installing backports 3.6.4
       Installing daemons 1.1.9
       Installing rack 1.5.2
       Installing thread_safe 0.3.4
       Installing sass 3.2.19
       Installing multi_json 1.10.1
       Installing tilt 1.4.1
       Installing hike 1.2.3
       Installing thor 0.18.1
       Installing equalizer 0.0.9
       Installing multipart-post 2.0.0
       Installing json 1.8.1
       Installing http_parser.rb 0.6.0
       Installing naught 1.0.0
       Installing rails_serve_static_assets 0.0.2
       Installing libv8 3.16.14.7
       Installing ref 1.0.5
       Installing rails_stdout_logging 0.0.3
       Installing simple_oauth 0.3.0
       Using bundler 1.6.3
       Installing coffee-script 2.2.0
       Installing rack-protection 1.5.3
       Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
       /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/ruby-1.9.3/bin/ruby extconf.rb
       checking for load library path...
       LD_LIBRARY_PATH is not set.
       checking ld.so.conf... no
       checking for cc... ok
       checking for gcc... yes
       checking for LP64... yes
       checking for sys/types.h... yes
       checking for ruby header... ok
       *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of
       necessary libraries and/or headers.  Check the mkmf.log file for more
       details.  You may need configuration options.
       Provided configuration options:
       --with-opt-dir
       --without-opt-dir
       --with-opt-include
       --without-opt-include=${opt-dir}/include
       --with-opt-lib
       --without-opt-lib=${opt-dir}/lib
       --with-make-prog
       --without-make-prog
       --srcdir=.
       --curdir
       --ruby=/tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/ruby-1.9.3/bin/ruby
       --with-instant-client
       --without-instant-client
       /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:891:in `get_home': RuntimeError (RuntimeError)
       from /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:707:in `initialize'
       from /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:320:in `new'
       from /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:320:in `get'
       from extconf.rb:18:in `<main>'
       ---------------------------------------------------
       Error Message:
       Set the environment variable ORACLE_HOME if Oracle Full Client.
       Append the path of Oracle client libraries to LD_LIBRARY_PATH if Oracle Instant Client.
       
       Backtrace:
       /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:891:in `get_home'
       /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:707:in `initialize'
       /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:320:in `new'
       /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:320:in `get'
       extconf.rb:18:in `<main>'
       ---------------------------------------------------
       See:
       * http://rubydoc.info/gems/ruby-oci8/file/docs/install-full-client.md for Oracle full client
       * http://rubydoc.info/gems/ruby-oci8/file/docs/install-instant-client.md for Oracle instant client
       * http://ruby-oci8.rubyforge.org/en/file.report-installation-issue.html to report an issue.
       Gem files will remain installed in /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7 for inspection.
       Results logged to /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/gem_make.out
       Installing rack-test 0.6.2
       Installing eventmachine 1.0.3
       An error occurred while installing ruby-oci8 (2.1.7), and Bundler cannot
       continue.
       Make sure that `gem install ruby-oci8 -v '2.1.7'` succeeds before bundling.
       Bundler Output: Fetching gem metadata from https://rubygems.org/...........
       Resolving dependencies...
       Installing buftok 0.2.0
       Installing addressable 2.3.6
       Installing coffee-script-source 1.8.0
       Installing execjs 2.0.2
       Installing backports 3.6.4
       Installing daemons 1.1.9
       Installing rack 1.5.2
       Installing thread_safe 0.3.4
       Installing sass 3.2.19
       Installing multi_json 1.10.1
       Installing tilt 1.4.1
       Installing hike 1.2.3
       Installing thor 0.18.1
       Installing equalizer 0.0.9
       Installing multipart-post 2.0.0
       Installing json 1.8.1
       Installing http_parser.rb 0.6.0
       Installing naught 1.0.0
       Installing rails_serve_static_assets 0.0.2
       Installing libv8 3.16.14.7
       Installing ref 1.0.5
       Installing rails_stdout_logging 0.0.3
       Installing simple_oauth 0.3.0
       Using bundler 1.6.3
       Installing coffee-script 2.2.0
       Installing rack-protection 1.5.3
       
       Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
       
       /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/ruby-1.9.3/bin/ruby extconf.rb
       checking for load library path...
       LD_LIBRARY_PATH is not set.
       checking ld.so.conf... no
       checking for cc... ok
       checking for gcc... yes
       checking for LP64... yes
       checking for sys/types.h... yes
       checking for ruby header... ok
       *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of
       necessary libraries and/or headers.  Check the mkmf.log file for more
       details.  You may need configuration options.
       
       Provided configuration options:
       --with-opt-dir
       --without-opt-dir
       --with-opt-include
       --without-opt-include=${opt-dir}/include
       --with-opt-lib
       --without-opt-lib=${opt-dir}/lib
       --with-make-prog
       --without-make-prog
       --srcdir=.
       --curdir
       --ruby=/tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/ruby-1.9.3/bin/ruby
       --with-instant-client
       --without-instant-client
       /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:891:in `get_home': RuntimeError (RuntimeError)
       from /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:707:in `initialize'
       from /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:320:in `new'
       from /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:320:in `get'
       from extconf.rb:18:in `<main>'
       ---------------------------------------------------
       Error Message:
       Set the environment variable ORACLE_HOME if Oracle Full Client.
       Append the path of Oracle client libraries to LD_LIBRARY_PATH if Oracle Instant Client.
       
       Backtrace:
       /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:891:in `get_home'
       /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:707:in `initialize'
       /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:320:in `new'
       /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/oraconf.rb:320:in `get'
       extconf.rb:18:in `<main>'
       ---------------------------------------------------
       See:
       * http://rubydoc.info/gems/ruby-oci8/file/docs/install-full-client.md for Oracle full client
       * http://rubydoc.info/gems/ruby-oci8/file/docs/install-instant-client.md for Oracle instant client
       * http://ruby-oci8.rubyforge.org/en/file.report-installation-issue.html to report an issue.
       
       
       
       Gem files will remain installed in /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7 for inspection.
       Results logged to /tmp/build_7ce55682205351c02148db0b8dad96c5/vendor/bundle/ruby/1.9.1/gems/ruby-oci8-2.1.7/ext/oci8/gem_make.out
       Installing rack-test 0.6.2
       Installing eventmachine 1.0.3
       An error occurred while installing ruby-oci8 (2.1.7), and Bundler cannot
       continue.
       Make sure that `gem install ruby-oci8 -v '2.1.7'` succeeds before bundling.
 !
 !     Failed to install gems via Bundler.
 !

 !     Push rejected, failed to compile Ruby app

**Comment by tylermauthe** [comment]
The gem you are using requires the environment to provide some of it's functionality through a dependency. Heroku doesn't have the proper Oracle client libraries installed by default. You would need to use a custom buildpack for this.

Try something like this:
https://github.com/nasali/oracle-oci8-heroku-buildpack
