### ISSUE TITLE
Number widget refresh data

### ISSUE THREAD

**Issue by Mitsumi** [Shopify/dashing#495]
I try to fetch and display our Aruba wlan user numbers through snmp. The job is created and the data injected in the widget, but after a few minutes data keeps coming in, but the browser widget number stops refreshing. 

![dashingio](https://cloud.githubusercontent.com/assets/3251596/5488579/167d83de-86c0-11e4-8ac6-a83f2ade1542.PNG)

SCHEDULER.every '10s', :first_in => 0 do |job|
  
master = `snmpget -v2c -c zenoss 10.99.0.103.1.3.6.1.4.1.14823.2.2.1.4.1.1.0 | awk '{printf $4}'`
slave = `snmpget -v2c -c zenoss 10.99.0.104 .1.3.6.1.4.1.14823.2.2.1.4.1.1.0 | awk '{printf $4}'`
number = master.to_i + slave.to_i
    
last_master= master.to_i
last_slave = slave.to_i
last_number = number.to_i
    
sleep(5)
    
master = `snmpget -v2c -c zenoss 10.99.0.103 .1.3.6.1.4.1.14823.2.2.1.4.1.1.0 | awk '{printf $4}'`
slave = `snmpget -v2c -c zenoss 10.99.0.104 .1.3.6.1.4.1.14823.2.2.1.4.1.1.0 | awk '{printf $4}'`
number = master.to_i + slave.to_i
     
send_event('wlan-users-total', { current: number, last: last_number })
send_event('wlan-users-master', {current: master, last: last_master})
send_event('wlan-users-slave', {current: slave, last: last_slave})
end

OS: Linux Ubuntu
Browser: Firefox & Chrome

**Comment by Mitsumi** [comment]
Problem still exists, any suggestions?

**Comment by tylermauthe** [comment]
@Mitsumi is the correct value shown when you refresh the page, as it is for @ykyuen ?

**Comment by Mitsumi** [comment]
@tylermauthe, When I refresh the page, the correct values are displayed.
In console I can see the updates values comming in, but they are not 'refreshed' into the widget.

**Comment by tylermauthe** [comment]
Perhaps the browsers JavaScript engine is becoming thrashed somehow? That
shouldn't happen right away under normal circumstances.

How long before this starts happening?

**Comment by tylermauthe** [comment]
~~Perhaps the browsers JavaScript engine is becoming thrashed somehow? That
shouldn't happen right away under normal circumstances.~~  -- If the console is still outputting stuff, the JS engine cannot be thrashed.

Try setting a breakpoint inside the number widget's onData and step through... Perhaps it is being updated momentarily and then being overwritten?

Is this a stock number widget, or does it have modifications?

**Comment by tylermauthe** [comment]
If you can create a publicly available example of this happening I will take a crack at debugging it.

Otherwise I can only recommend to workaround this issue by [sending a refresh every now and then](https://gist.github.com/jwalton/6616670#comment-1366590).

Please update this issue with a URL to an example of this or close this issue.

**Comment by tylermauthe** [comment]
Please close this issue.
