### ISSUE TITLE
Setting foreground on meter widget

### ISSUE THREAD

**Issue by devilldog** [Shopify/dashing#497]
All, I am trying to set the foreground of the meter widget based on a value. I have tried what was suggested for the background ( evaluating the value at onData but cannot seem to get it work I just get a blank screen. What i would really like rather then the entire foreground would be just the arc changes color. Below is what i had tried. Thanks !
```ruby
 onData: (value) ->
    if value >= 85
      $(@node).css('foreground-color', '#fff')
    else
      $(@node).css('foreground-color', "color")
    end
```

**Comment by devilldog** [comment]
anyone have a fix for me ? thanks !

**Comment by tylermauthe** [comment]
```
meter = $(@node).find(".meter")
meter.trigger('configure',
   'fgColor': '#00FF00'
)
```
