### ISSUE TITLE
HTML variable in Ruby Job

### ISSUE THREAD

**Issue by tclass** [Shopify/dashing#500]
Is it possible to retrieve the HTML Attributes in the Ruby Job? I have to pass values from the dashboard to the underlying job

**Comment by tclass** [comment]
nvm I solved it

**Comment by MartynKeigher** [comment]
Hey @tclass, mind sharing with the rest of the class you did this?? ;p

Thanks.

**Comment by tclass** [comment]
I thought I had to pass values via HTML Attributes to the Jobs, but I realized I didn't have to do that, I just can fire up events and the right widget will get the result, so I created a config file and added some information about some widgets and just imported the config in my jobs. So I didn't pass any values from HTML to the Ruby Jobs, but if you have a problem just make an issue and link it here, I'm happy to help.
