### ISSUE TITLE
`bundle install`: Could not find thor-0.18.1.20140116 in any of the sources

### ISSUE THREAD

**Issue by tjhorner** [Shopify/dashing#507]
When I deploy to Heroku, I get this error:

```
-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.0.0
-----> Installing dependencies using 1.7.12
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from https://rubygems.org/.........
       Could not find thor-0.18.1.20140116 in any of the sources
       Bundler Output: Fetching gem metadata from https://rubygems.org/.........
       Could not find thor-0.18.1.20140116 in any of the sources
 !
 !     Failed to install gems via Bundler.
 !
```

Bad dependency version I'm guessing. Any way I can change it to `thor-0.18.1` instead of `thor-0.18.1.20140116`?

**Comment by tylermauthe** [comment]
I just created a brand new dashboard and was able to push it to Heroku no problem. You must have changed something either in your Gemfile or your Gemfile.lock.

Please compare those files with a fresh instance and see if that helps you track down the issue.

**Comment by tjhorner** [comment]
Forgot about this issue, it was something in my `Gemfile`. I have no idea what, but creating a new dashboard and copying over the widgets solved it.
