### ISSUE TITLE
Multiple CSS views with a single widget using selectors

### ISSUE THREAD

**Issue by visser23** [Shopify/dashing#508]
Hi all,

So I am currently trying to use a DIV ID to create a different view using a single widget.

In this example, I would like to set an ID within the erb dashboard file like so: 

      <div id="weekly" data-id="etvvrb" data-view="Rickshawgraph" data-title="Weekly ETV reach" data-moreinfo="Week commencing"></div>

and in the SCSS file, stipulate the different view...

    .x_tick {
    position: absolute;
    bottom: 0;
    fill: $tick-color;

    .title {
      font-size: 20px;
      color: $tick-color;
      opacity: 0.5;
      padding-bottom: 3px;
     }
    }

    #weekly.x_tick  {   
    position: absolute;
    bottom: 0;
    fill: $tick-color;

      .title {
      font-size: 9px;
      color: $tick-color;
      opacity: 0.5;
      padding-bottom: 3px;
      writing-mode:tb-rl;
      -webkit-transform:rotate(90deg);
      -moz-transform:rotate(90deg);
      -o-transform: rotate(90deg);
      -ms-transform:rotate(90deg);
      white-space:nowrap;
      display:block;
      bottom:0;
      width:0.5px;
      height:20px;
     }
    }

My understanding is that the x_tick for the 'weekly' id selector should override the standard x_tick, but it seems to have no effect at all. I think this may be due to it not quite matching up as I expect in Dashing. Does anybody have any ideas?

**Comment by tylermauthe** [comment]
The #weekly div doesn't have a .x_tick class, so your CSS rule is wrong.

I think you probably want `#weekly .xtick`.

**Comment by visser23** [comment]
I've figured it out.

Dashing will generate a class object which is based on both the data-id and data-view tags (probably via JS but I may be wrong there).

This will come out looking something like data-view_widget.data-id.

This means that you can create a new class in your CSS document using the element generated by JS. In my case, this would look something like:

       .widget-rickshawgraph {
           /* CSS stuff */
        }

       .widget-rickshawgraph.DATA-ID {
            .x_tick > .title {
          /* CSS overwrite */
       } 

Hope that makes sense. Thanks :)

**Comment by tylermauthe** [comment]
Sounds good, that is a more general solution.

Please close this issue.
