### ISSUE TITLE
How to pass variable from config.ru to another .erb file ?

### ISSUE THREAD

**Issue by pol0nium** [Shopify/dashing#509]
Hi, this question is similar to #127 but the answer didn't work for my case.

I want to load a new page with more precise informations when clicking on a widget.

I did the following : 
- create a custom widget with a form and a POST action
- add the following code in `config.ru`:
```ruby
    post '/details' do
      # some code
      Sinatra::Application::TEMPERATURE = temperature
      erb :details
    end
```
- add the following code in `details.erb`:
    <%= TEMPERATURE %>

In this case, the variable `TEMPERATURE` is not set in `details.erb`.

I also tried to use `@temperature`, `@@temperature` and `erb :details, :locals => {:temperature => temperature}` but still cannot access this value in the .erb file.

Is there a way to do that ?

Regards,

**Comment by tylermauthe** [comment]
I believe the issue is that you are trying to define a route that is already matched by Dashing's /:dashboard route.

Try doing something like:
```ruby
post '/temperature/details' do
   # find temp
   @temperature = temp
   erb :details
end

#inside ERB:
<%= @temperature %>
```

Note that you'll also be able to go to /details unless you guard against this in your ERB by analysing the path...

I found this out by [exploring the Dashing source code](https://github.com/Shopify/dashing/blob/master/lib/dashing/app.rb).

**Comment by tylermauthe** [comment]
It just occurred to me that probably a better solution to this is to create a helper method that calculates the temperature.

Something like this (untested):
```ruby
  #config.ru
  helpers do
    # ...
    def getTemperatureDetails(item)
      # get temperature details for item
      return temperature
    end
  end

  #details.erb
  <%= getTemperatureDetails(params[:item]) %>
```

**Comment by pol0nium** [comment]
Thanks, that are definitely the answers I was looking for.
