### ISSUE TITLE
behind firewall

### ISSUE THREAD

**Issue by martyni** [Shopify/dashing#512]
Hello

I am trying to connect to a dashing instance on the other side of my works firewall. I can connect to the page but the data isn't being populated. 

Can you advise why this is not working?

Cheers 

Martyn

**Comment by cefigueiredo** [comment]
You need ensure that your firewall let `event-stream` MIME type pass, and that your firewall does not close the connection.
Dashing works based on [Server Sent Events](https://developer.mozilla.org/en-US/docs/Server-sent_events), so you need search discover how configure your firewall to let it pass freely.

**Comment by tylermauthe** [comment]
Any updates on this issue?
