### ISSUE TITLE
Working on building a JQPlot widget set...some questions

### ISSUE THREAD

**Issue by ilikenwf** [Shopify/dashing#517]
The company I work for, DMP, is having me build JQPlot widgets for dashing, with the later intent of sharing them with the community. Before I can really build beyond this initial widget though, I need to figure out some issues.

I already have JQPlot graphs and such working in dashing, however I am currently limited to one of each widget because jqplot expects an element to have a unique ID - while it's documentation shows it supporting jquery selectors, this doesn't work because it still expects to bind to an element ID, from my tests, or the way coffeescript generates js is somehow preventing the plugin from properly using the class based version of such a widget, with an object.

Any ideas on a way of doing this in such a way that I don't have to create multiple copies of the same widget, just to change the id's?

The other main problem is that jqplot distributes everything other than basic charts in plugin files. While dashing happily will consume them, the way (or the order?) that they are compiled into application.js seems to prevent jqplot from seeing them. As such, I'm forced to either merge the plugin code into the mainline jqplot js file, or not use it...again, any ideas here? If the issue is ordering, is there a way to set the order that js files are loaded and merged in dashing?

I really want to get these built and shared, but until I figure out these issues, I'm hesitant to do so since the code is half-baked...I'm not really much on coffeescript and so I'm sure they will need some community suggestions later on anyway. 

The one I have closest to done at the moment is the simple speedometer "meter," but there are other jqplot chart types that are not yet built as widgets for Dashing. I realize there is rickshaw, which we already use, but for some simple charts and other applications, it will be nice to have the full complement of tools that jqplot provides.

Thank you Shopify, for the great software!

**Comment by tylermauthe** [comment]
It's wonderful to see a company giving back to OpenSource -- cheers!

After sifting through your message, it seems like you have these issues:
1. jqPlot expects each graph element to have a unique ID
2. JavaScript dependency load order

For #1:
An understanding of how jQuery and jQuery plugins work would be beneficial, specifically this: http://stackoverflow.com/questions/8884463/jqplot-target-that-doesnt-have-a-static-id

For #2:
Dashing uses Sprockets to manage client-side dependencies (like CSS and JS). If you open application.coffee you'll see:

```coffeescript
#= require_directory .
#= require_tree ../../widgets
```

You need to add your dependencies above the `require_directory` line. Something like:
```coffeescript
#= require jqueryPlugin1
#= require jqueryPlugin2
#= require_directory .
#= require_tree ../../widgets
```

**Comment by ilikenwf** [comment]
Well, for #1 even that post says that jqplot creates a unique id if one isn't assigned to the object; my problem is that using $(@node).jqplot(...) method of doing things does not work and I am unsure why. We can't use classes because doing so would apply the same data to all jqplot instances, when we likely have different data for each widget in for the purposes of dashing.

For #2: thank you!

**Comment by tylermauthe** [comment]
For # 1:

I apologise if I assumed your knowledge of jQuery was limited. As you know, proper jQuery plugins should be available on $.fn.<plugin>. This allows them to apply their functionality to a jQuery selection. Load up your Dashboard, in your browser console run `console.log($.fn.jqplot)`. What do you get back? You should see a function.

If you get `undefined`, you may be using an old version, as suggested in the the accepted answer for the SO I linked.

You can get the latest code from here:
https://bitbucket.org/cleonello/jqplot/

Browsing this source code seems to indicate that the bug in jqPlot that you're referring to has been fixed.

**Comment by tylermauthe** [comment]
Can you paste some code samples or put this up in a public repo? I think I'm just misunderstanding what you're asking for.

**Comment by ilikenwf** [comment]
No need to apologise! My knowledge of coffeescript is limited, though, so I still feel a bit like a caveman in some ways with this process.

$.fn.jqplot is there, I believe I have the latest milestone release. Maybe it is still behind somehow, I'll try the git version.

I'll gist the code later - I'm sure I'm doing some things wrong or inefficiently in places because of my lack of coffeescript experience, so I'm a bit self conscious since I write in other languages much more gracefully.

**Comment by tylermauthe** [comment]
haha, sounds good. Do you have multiple graph's per Dashing widget? I think you'll need to keep a handle on each of the Graph instances as a class variable of the widget so that you can update them in the onData like this:
http://stackoverflow.com/questions/10459631/jqplot-how-to-live-update-a-chart

**Comment by ilikenwf** [comment]
I have only a single graph per dashing widget, I have a handle on the one I create for each though, as I call replot after updating the data to redraw.

Feel free to laugh at my awful coffeescript. I may have an obvious issue here, but I don't see it:
https://gist.github.com/ilikenwf/3583b15c813a0ac2a221

**Comment by tylermauthe** [comment]
I'm just taking a quick look at it on my lunch break, but it looks like you're doing everything in a sane way.

I will make some time this evening to dig deeper into this. What is the undesired behaviour that you're seeing with this code? Is it giving errors or just not doing what you expect?

**Comment by ilikenwf** [comment]
Don't burn your personal time on this unless you really want to...

The problem is still that I can't call something like $(@node).jqplot() and am currently having to apply the plot by id, thus preventing me from using this one copy of the widget files for multiple widgets of the same type.

**Comment by tylermauthe** [comment]
Aha! It was such a small thing, I overlooked it several times before finding the main mistake.

`drawGraph` was not defined as a class method, meaning that it didn't have access to the other instance properties like `@node`.

So this:
```coffeescript
drawGraph = (val, buckets, bucketColors, reverse, sLabel, pos) ->    
    bucketColors.reverse() if reverse

    return $.jqplot("jqmeter", [[val]],
    grid: {background: 'transparent'}
    seriesDefaults:
      renderer: $.jqplot.MeterGaugeRenderer
      rendererOptions:
        label: sLabel
        labelPosition: pos
        showTickLabels: true
        intervals: buckets
        intervalColors: bucketColors
    )
```

Should be:
```coffeescript
  drawGraph: (val, buckets, bucketColors, reverse, sLabel, pos) ->
    bucketColors.reverse() if reverse

    blah = $(@node).find('.jqmeter').jqplot([[val]],
    grid: {background: 'transparent'}
    seriesDefaults:
      renderer: $.jqplot.MeterGaugeRenderer
      rendererOptions:
        label: sLabel
        labelPosition: pos
        showTickLabels: true
        intervals: buckets
        intervalColors: bucketColors
    )
```

I've modified `div#jqmeter` to be `div.jqmeter` in the HTML and I am using jQuery.fn.find after selecting `@node` to ensure that the data update is namespaced to the correct DOM element (IE: the widget). I'm also using jqPlot as a selector method, as indicated in the StackOverflow I linked earlier. 

Note that by making `drawGraph` a class method, you'll have to reference it like this: `@drawGraph`.

Hope this helps!

**Comment by ilikenwf** [comment]
Ah very nice, thank you! My ignorance of coffeescript seems to be at fault
here.

**Comment by ilikenwf** [comment]
Thanks! I can confirm this method works, between me not knowing coffee super well and starting at this thing for so long, I was blinded to the issue.

Thanks! I'll close the issue and try to get this put on a gist somewhere soon.
