### ISSUE TITLE
Any way to protect usage of dashboard?

### ISSUE THREAD

**Issue by m-baumgartner** [Shopify/dashing#518]
I know you can implement Google Auth, Github Auth or any custom Auth you'd like to implement to prevent who is accessing your dashboard.
What i'd like is to deploy a dashing instance on a site and be sure that no one will just copy my dashing directory and set up a new instance next to it without using my custom Auth. Is that possible?

**Comment by tylermauthe** [comment]
I'm not sure I'm fulling understanding your request, but I think that this is more of System Administration issue than a Dashing issue...

I would achieve this by enforcing system permissions on the folder.

**Comment by m-baumgartner** [comment]
I'll try to explain. I want to make a commercial user of a specific dashboard that i would create and deploy with the rest of our solution. This needs to be installed "on site", that basically means that i need to be sure nobody can duplicate the dashboard (and so the work i've put in) to avoid paying for it.
I think this is not against MIT right?
I could develop a specific Auth system in my solution but the client could always reset the config.ru and just avoid it.

**Comment by tylermauthe** [comment]
Oh, I got you. I don't know if it violates the license...

There are two approaches I would take to this:
1) Obfuscation - Make the auth code hard to remove / alter
2) Container / Appliance - Put the code into a VM or Container that has locked down permissions and 'just works' in their environment

Dashing certainly doesn't provide any functionality for licensing or restricting the number of running copies. You'll have to come up with some magic.

**Comment by m-baumgartner** [comment]
Thank you for your answers, i'll try to find something.
