### ISSUE TITLE
Timeseries - can Dashing create a graph

### ISSUE THREAD

**Issue by mattjerry** [Shopify/dashing#52]
I have seen a graph in the sample dashboard. 
I am using direct update of the dashboard data via REST. 
How do I frame a curl request to update the dashboard in timeseries.

In the code base for convergence graph for sample dashboard - but it doesnt indicate a timeseries.
# Populate the graph with some random points

points = [](1..10).each do |i|
  points << { x: i, y: rand(50) }
end
last_x = points.last[:x]

SCHEDULER.every '2s' do
  points.shift
  last_x += 1
  points << { x: last_x, y: rand(50) }

  send_event('convergence', points: points)
end

**Comment by bean5** [comment]
A note to future users, the ways mentioned here of updating a graph seem to be outdated. Sending the values as numbers rather than as strings seems to be more supported. So instead of this:

```
curl -d '{ "auth_token":"YOUR_AUTH_TOKEN", "points": 
[ { "x": "-1893456000", "y": "92228531" }, { "x": "-1577923200", "y": "106021568" }, { "x": "315532800", "y": "226545805" }, { "x": "631152000", "y": "248709873" } ] }'http://localhost:3030/widgets/convergence
```

You should do this:

```
curl -d '{ "auth_token":"YOUR_AUTH_TOKEN", "points": 
[ { "x": -1893456000, "y": 92228531 }, { "x": -1577923200, "y": 106021568 }, { "x": 315532800, "y": 226545805 }, { "x": 631152000, "y": 248709873 } ] }'http://localhost:3030/widgets/convergence
```
