### ISSUE TITLE
Tilt Errors in Every Widget

### ISSUE THREAD

**Issue by tithar** [Shopify/dashing#520]
I have a fresh install of Dashing. Just a base install and all of my widgets have them following content:

["str", [Tilt::StringTemplate]]["erb", [Tilt::ErubisTemplate, Tilt::ERBTemplate]]["rhtml", [Tilt::ErubisTemplate, Tilt::ERBTemplate]]["erubis", [Tilt::ErubisTemplate]]["etn", [Tilt::EtanniTemplate]]["etanni", [Tilt::EtanniTemplate]]["haml", [Tilt::HamlTemplate]]["mab", [Tilt::MarkabyTemplate]]["liquid", [Tilt::LiquidTemplate]]["radius", [Tilt::RadiusTemplate]]["markdown", [Tilt::RedcarpetTemplate, Tilt::RedcarpetTemplate::Redcarpet2, Tilt::RedcarpetTemplate::Redcarpet1, Tilt::RDiscountTemplate, Tilt::BlueClothTemplate, Tilt::KramdownTemplate, Tilt::MarukuTemplate]]["mkd", [Tilt::RedcarpetTemplate, Tilt::RedcarpetTemplate::Redcarpet2, Tilt::RedcarpetTemplate::Redcarpet1, Tilt::RDiscountTemplate, Tilt::BlueClothTemplate, Tilt::KramdownTemplate, Tilt::MarukuTemplate]]["md", [Tilt::RedcarpetTemplate, Tilt::RedcarpetTemplate::Redcarpet2, Tilt::RedcarpetTemplate::Redcarpet1, Tilt::RDiscountTemplate, Tilt::BlueClothTemplate, Tilt::KramdownTemplate, Tilt::MarukuTemplate]]["textile", [Tilt::RedClothTemplate]]["rdoc", [Tilt::RDocTemplate]]["wiki", [Tilt::WikiClothTemplate, Tilt::CreoleTemplate]]["creole", [Tilt::CreoleTemplate]]["mediawiki", [Tilt::WikiClothTemplate]]["mw", [Tilt::WikiClothTemplate]]["ad", [Tilt::AsciidoctorTemplate]]["adoc", [Tilt::AsciidoctorTemplate]]["asciidoc", [Tilt::AsciidoctorTemplate]]["htmf", [Tilt::PlainTemplate]]

I've read all the other threads about naming being an issue, but this is literally a fresh install, no extra widgets, nothing extra so I'm not seeing where I could have any issues with naming. I've checked all the widgets folders and they are named correctly.

Running on Windows 7 and I've tried Ruby 1.9.3 and Ruby 2.1

Gemfile.lock:

specs:
    addressable (2.3.7)
    atomic (1.1.99)
    backports (3.6.4)
    buftok (0.2.0)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.4.0)
    daemons (1.0.9)
    dashing (1.3.4)
      coffee-script (~> 2.2.0)
      execjs (~> 2.0.2)
      rack (~> 1.5.2)
      rufus-scheduler (~> 2.0.24)
      sass (~> 3.2.12)
      sinatra (~> 1.4.4)
      sinatra-contrib (~> 1.4.2)
      sprockets (~> 2.10.1)
      thin (~> 1.6.1)
      thor (~> 0.18.1)
    equalizer (0.0.9)
    eventmachine (1.0.7)
    execjs (2.0.2)
    faraday (0.9.0)
      multipart-post (>= 1.2, < 3)
    hike (1.2.0)
    http (0.6.0)
      http_parser.rb (~> 0.6.0)
    http_parser.rb (0.6.0)
    json (1.8.0)
    memoizable (0.4.0)
      thread_safe (~> 0.1.3)
    multi_json (1.10.1)
    multipart-post (1.2.0)
    naught (1.0.0)
    rack (1.5.2)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rufus-scheduler (2.0.24)
      tzinfo (>= 0.3.22)
    sass (3.2.12)
    simple_oauth (0.2.0)
    sinatra (1.4.5)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (~> 1.3, >= 1.3.4)
    sinatra-contrib (1.4.2)
      backports (>= 2.0)
      multi_json
      rack-protection
      rack-test
      sinatra (~> 1.4.0)
      tilt (~> 1.3)
    sprockets (2.10.1)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    thin (1.6.1)
      daemons (>= 1.0.9)
      eventmachine (>= 1.0.0)
      rack (>= 1.0.0)
    thor (0.18.1)
    thread_safe (0.1.3)
      atomic
    tilt (1.3.4)
    twitter (5.9.0)
      addressable (~> 2.3)
      buftok (~> 0.2.0)
      equalizer (~> 0.0.9)
      faraday (~> 0.9.0)
      http (~> 0.6.0)
      http_parser.rb (~> 0.6.0)
      json (~> 1.8)
      memoizable (~> 0.4.0)
      naught (~> 1.0)
      simple_oauth (~> 0.2.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)

PLATFORMS
  x86-mingw32

DEPENDENCIES
  dashing
  twitter (>= 5.9.0)

**Comment by frounzn** [comment]
Check the widgets directory. The folders there should have the same name like the files. For example: 
```
meter
meter/meter.coffee
meter/meter.scss
meter/meter.html
```

**Comment by tithar** [comment]
Yep. Every folder, the files match the name of the folder.

**Comment by amassaad** [comment]
Are you able to run other ruby or rails apps? What command are you running when you get an error?

**Comment by tithar** [comment]
This is my first install on the Windows side, I have it running perfectly on an Ubuntu server.

I run "dashing start" and I get no errors.

Then when I browse to http://localhost:3030/sample all the widgets are filled with that error text.

**Comment by amassaad** [comment]
Hmm, odd. What browser are you seeing this with? Since its working elsewhere, and for others, I would say this is not related to Dashing but more about the installation on the windows side or the browser accessing the server.

**Comment by tithar** [comment]
I don't think I was clear and this was closed prematurely... I have a separate dashing instance on an Ubuntu server that works.

On this Windows install, it doesn't work with any browser.

**Comment by amassaad** [comment]
Hi @tithar our focus with gather issues is intended to look into problems with the code in Dashing and not troubleshoot installations. 

I can for sure ping a few more ideas over to solve this on your end possibly, but it doesn't seem to be an issue with the Dashing framework. 

 I am thinking there is a problem with your specific installation on the Windows side. Have you been able to run other rails apps successfully? For example how are you managing gems? This may be one of the issues, and testing if another app works will point to the system libraries or your Dashing files as the next avenue to test.

The Dashing gem is only providing some basic framework which is used by (previously installed) libraries on your system to create the web server, render the templates, run the jobs etc.

Once you verify you have Ruby and Rails setup correctly this might help with some background info as they were able to resolve this by adjusting the file names in the installation: https://github.com/Shopify/dashing/issues/324
