### ISSUE TITLE
uninitialized constant SCHEDULER (NameError)

### ISSUE THREAD

**Issue by michaelfree** [Shopify/dashing#529]
I seem to be having some issues with my Dashing setup.  It appears as though none of the widgets are updating once they’re added to the erb file. 

My setup/install of dashing went as follows in Ubuntu 14.04 LTS:
> #: apt-get install ruby ruby-dev nodejs build-essential bundler &&  gem install rufus-scheduler && gem install dashing

Afterwards, I created a new dashboard:
> $: dashing new testboard 

Response is:
>     create  testboard
      create  testboard/.gitignore
      create  testboard/Gemfile
      create  testboard/README.md
      create  testboard/assets/fonts/fontawesome-webfont.eot
      create  testboard/assets/fonts/fontawesome-webfont.svg
      create  testboard/assets/fonts/fontawesome-webfont.ttf
      create  testboard/assets/fonts/fontawesome-webfont.woff
      create  testboard/assets/images/logo.png
      create  testboard/assets/javascripts/application.coffee
      create  testboard/assets/javascripts/d3-3.2.8.js
      create  testboard/assets/javascripts/dashing.gridster.coffee
      create  testboard/assets/javascripts/gridster/jquery.gridster.js
      create  testboard/assets/javascripts/gridster/jquery.leanModal.min.js
      create  testboard/assets/javascripts/jquery.knob.js
      create  testboard/assets/javascripts/rickshaw-1.4.3.min.js
      create  testboard/assets/stylesheets/application.scss
      create  testboard/assets/stylesheets/font-awesome.css
      create  testboard/assets/stylesheets/jquery.gridster.css
      create  testboard/config.ru
      create  testboard/dashboards/layout.erb
      create  testboard/dashboards/sample.erb
      create  testboard/dashboards/sampletv.erb
      create  testboard/jobs/buzzwords.rb
      create  testboard/jobs/convergence.rb
      create  testboard/jobs/sample.rb
      create  testboard/jobs/twitter.rb
      create  testboard/lib
      create  testboard/public/404.html
      create  testboard/public/favicon.ico
      create  testboard/widgets/clock/clock.coffee
      create  testboard/widgets/clock/clock.html
      create  testboard/widgets/clock/clock.scss
      create  testboard/widgets/comments/comments.coffee
      create  testboard/widgets/comments/comments.html
      create  testboard/widgets/comments/comments.scss
      create  testboard/widgets/graph/graph.coffee
      create  testboard/widgets/graph/graph.html
      create  testboard/widgets/graph/graph.scss
      create  testboard/widgets/iframe/iframe.coffee
      create  testboard/widgets/iframe/iframe.html
      create  testboard/widgets/iframe/iframe.scss
      create  testboard/widgets/image/image.coffee
      create  testboard/widgets/image/image.html
      create  testboard/widgets/image/image.scss
      create  testboard/widgets/list/list.coffee
      create  testboard/widgets/list/list.html
      create  testboard/widgets/list/list.scss
      create  testboard/widgets/meter/meter.coffee
      create  testboard/widgets/meter/meter.html
      create  testboard/widgets/meter/meter.scss
      create  testboard/widgets/number/number.coffee
      create  testboard/widgets/number/number.html
      create  testboard/widgets/number/number.scss
      create  testboard/widgets/text/text.coffee
      create  testboard/widgets/text/text.html
      create  testboard/widgets/text/text.scss
As defined in the installation/setup instructions I then go to my newly created directory and bundle it

> $: cd testboard && bundle

Response: 
> Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Enter your password to install the bundled RubyGems to your system: 
Using addressable (2.3.7) 
Using backports (3.6.4) 
Using buftok (0.2.0) 
Using coffee-script-source (1.9.1) 
Using execjs (2.0.2) 
Using coffee-script (2.2.0) 
Using daemons (1.1.9) 
Using rack (1.5.2) 
Using thread_safe (0.3.4) 
Using tzinfo (1.2.2) 
Using rufus-scheduler (2.0.24) 
Using sass (3.2.19) 
Using rack-protection (1.5.3) 
Using tilt (1.4.1) 
Using sinatra (1.4.5) 
Using multi_json (1.11.0) 
Using rack-test (0.6.3) 
Using sinatra-contrib (1.4.2) 
Using hike (1.2.3) 
Using sprockets (2.10.2) 
Using eventmachine (1.0.7) 
Using thin (1.6.3) 
Using thor (0.18.1.20140116) 
Using dashing (1.3.4) 
Using equalizer (0.0.9) 
Using multipart-post (2.0.0) 
Using faraday (0.9.1) 
Using http_parser.rb (0.6.0) 
Using http (0.6.3) 
Using json (1.8.2) 
Using memoizable (0.4.2) 
Using naught (1.0.0) 
Using simple_oauth (0.3.1) 
Using twitter (5.14.0) 
Using bundler (1.3.5) 
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.

Everything seems to be fine, so I start the server:
> $: dashing start

I then navigated to http://localhost:3030/sample and the sample dashboard had all of the widgets present on it. All of the sample widgets appear to be updating. 
Later, when I install new widgets that I wanted to try out, all were installed with the suggested syntax:

> $: dashing install GIST_ID

After that I remove the sample widgets from the erb file so it looks like this:

> <% content_for :title do %>My super sweet dashboard<% end %>
<div class="gridster">
  <ul>
  </ul>
  <center><div style="font-size: 12px">Try this: curl -d '{ "auth_token": "YOUR_AUTH_TOKEN", "text": "Hey, Look what I can do!" }' \http://<%=request.host%>:<%=request.port%>/widgets/welcome</div></center>
</div>

And then add the appropriate <li> tags  in between the <ul> ones and navigate back to to http://localhost:3030/sample - and the new widget appears. 

For each new widget I seem to add, the widget does infact appear – but they don’t appear to be updating at all.  

I tried running each ruby script individually in the terminal 
> $: ruby scriptname.rb

Each one returns the exact same result:
> jobs/scriptname.rb:19:in `<main>': uninitialized constant SCHEDULER (NameError)

Is this likely an issue with rufus-scheduler not being properly defined or setup properly?

Thanks,
Michael

**Comment by amassaad** [comment]
Hi Michael,

It sounds as if perhaps the widget and job are not aligned, they need to be using the same name to get the data so perhaps something has shifted when you installed the gist, or perhaps the gist requires more setup to actually send data.

Running the script specifically will return that error. SCHEDULER is initialized by the Dashing framework as a constant of Rufus scheduler to run jobs. Running just the job wouldn't include that as is done on line 4 and 11 here: https://github.com/Shopify/dashing/blob/master/lib/dashing/app.rb#L11

Perhaps adding those lines to your scriptname.rb might get it running to show what the issue is? Likely they are running fine and just not sending to a valid dashboard data-id

**Comment by phoet** [comment]
@amassaad this is also an issue with the `dashing job` command

on a vanilla generated instance

```bash
○ → be dashing --help
Commands:
  dashing generate (widget/dashboard/job) NAME  # Creates a new widget, dashboard, or job.
  dashing help [COMMAND]                        # Describe available commands or one specific command
  dashing install GIST_ID                       # Installs a new widget from a gist.
  dashing job JOB_NAME AUTH_TOKEN(optional)     # Runs the specified job. Make sure to supply your auth token if you have one set.
  dashing new PROJECT_NAME                      # Sets up ALL THE THINGS needed for your dashboard project.
  dashing start                                 # Starts the server in style!
  dashing stop                                  # Stops the thin server


 |2.2.2| uschis-workstation in ~/jimdo/sweet_dashboard_project
○ → be dashing generate job testo
       exist  jobs
      create  jobs/testo.rb

 |2.2.2| uschis-workstation in ~/jimdo/sweet_dashboard_project
○ → be dashing job testo
/Users/peter/jimdo/sweet_dashboard_project/jobs/testo.rb:2:in `<top (required)>': uninitialized constant SCHEDULER (NameError)
	from /Users/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/dashing-1.3.4/lib/dashing/cli.rb:106:in `require'
	from /Users/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/dashing-1.3.4/lib/dashing/cli.rb:106:in `require_file'
	from /Users/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/dashing-1.3.4/lib/dashing/cli.rb:78:in `job'
	from /Users/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Users/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Users/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Users/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Users/peter/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/dashing-1.3.4/bin/dashing:9:in `<top (required)>'
	from /Users/peter/.rbenv/versions/2.2.2/bin/dashing:23:in `load'
	from /Users/peter/.rbenv/versions/2.2.2/bin/dashing:23:in `<main>'
```

the code that you linked to should be part of the general bootstrapping of the app.

what i did was wrapping it up an a rake-task (with the addition of loading dotenv):

```
desc "run your job directly for testing"
task :run_job, [:job_name] do |task, args|
  require 'dotenv'
  Dotenv.load

  require 'dashing/cli'
  require 'dashing/downloader'
  Dashing::CLI.start(['job', args[:job_name]])

  SCHEDULER.join
end
```

from my point of view, the `dashing job JOB_NAME AUTH_TOKEN(optional)` is broken at the moment.

**Comment by leonardinius** [comment]
+1 I've had the same ftw moment.
I use standard cli tools to create a _working_ skeleton, only to find out that it does not work as intended

**Comment by guckykv** [comment]
+1

Same here. New installation on debian. If I try to start the original "sample" job:

```
$ dashing job sample
/srv/dashing/testing-dash/jobs/sample.rb:4:in `<top (required)>': uninitialized constant SCHEDULER (NameError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/cli.rb:106:in `require_file'
	from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/cli.rb:78:in `job'
	from /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /var/lib/gems/1.9.1/gems/dashing-1.3.4/bin/dashing:9:in `<top (required)>'
	from /usr/local/bin/dashing:23:in `load'
	from /usr/local/bin/dashing:23:in `<main>'
```

Same problems with my own jobs.

System:
```bash
$ cat /etc/debian_version 
7.8
$ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
$ gem list | grep dashing
dashing (1.3.4)
$ gem list | grep scheduler
rufus-scheduler (2.0.24)
```

So there is no way to automatically update my dashboard with jobs?
