### ISSUE TITLE
batman.js view filters not working

### ISSUE THREAD

**Issue by dacrome** [Shopify/dashing#530]
The batman.js [view filters](http://batmanjs.org/docs/api/batman.view_filters.html) are not working because dashing is using [version 0.14.1] (https://github.com/Shopify/dashing/blob/master/javascripts/batman.js#L16). Any chance to update to the latest [0.16.0] (https://github.com/batmanjs/batman/releases)? I'm not familiar with creating a gem by myself and I don't know if dashing is working with the latest batman.js release, but maybe I just have to replace the batman.js script?

**Comment by cefigueiredo** [comment]
I don't think so. 
Batman.js is not maintained anymore, and I guess that if they change Batman.js current version, they will replace it for another framework.

**Comment by dacrome** [comment]
yes, that's what I realized yesterday when I checked the open issues like https://github.com/Shopify/dashing/issues/498 and the referenced commit https://github.com/alssndro/dashing/commit/17aff6e3942ddd931106783ed0b1b67e68b36ebb. I just wrote a little script that fit my needs. Anyway, thanks for the feedback.

**Comment by fgimian** [comment]
Just wanted to add a little voice to the crowd here.  Having batman outdated in dashing is really confusing.  I honestly have spent hours today trying to understand why my code wasn't working. I have read the batman documentation at http://batmanjs.org/docs/api/batman.view_filters.html at least a half dozen times.

I understand that batman is not the way forward, but it would be great to at least have it at the latest version as a stopgap measure until dashing 2.x is released with a new integrated framework.

Cheers
Fotis

**Comment by tylermauthe** [comment]
Dashing 2.0 is probably going to use React.

There are some interesting forks to this end: @FlorianZ - 2dce07309581b04e8f1070517f835a4aa2b7f01c
