### ISSUE TITLE
Dashing Weather Radar Widget - HELP?

### ISSUE THREAD

**Issue by rickleigh** [Shopify/dashing#533]
Hello,

I have been searching high and low for someone that might have made a widget that would display a live weather radar display. I have had no luck finding such a thing and have no skills on how to go about making one. It may be as simple as using the iframes widget but I can't even seem to get that working either.

Would anyone be able to guide me on how I can accomplish this?

Thanks for any help,

-Rick

**Comment by kmiller-gh** [comment]
I have used the BigImage widget and Weather Underground's API.  Just need to refresh the page or create a job to download the latest images.  There are a few variables you can use to change the image a bit.  Just take a look at their documentation.

    <li data-row="1" data-col="1" data-sizex="2" data-sizey="2">
      <div data-id="picture" data-view="BigImage" data-image="http://api.wunderground.com/api/[MYAPIKEY]/animatedradar/q/NJ/Atlantic_City.gif?width=750&height=690&newmaps=1" style="background-color:transparent;" data-max="true"></div>
    </li>

**Comment by rickleigh** [comment]
Thank you for the information and I'll give it a look.

**Comment by rickleigh** [comment]
This worked perfectly! Thanks again!

**Comment by benglerum** [comment]
What did you do to get this to work? I copied and pasted the text to my erb file and got an API key, but nothing pops up...

**Comment by benglerum** [comment]
What exactly did you have to do to get this to work? I'm getting a blank screen. Is there a widget that goes along with it that i need to create?
