### ISSUE TITLE
Are mulitple dashboard instances a problem?

### ISSUE THREAD

**Issue by mattb77** [Shopify/dashing#537]
Apologies in advance if this isn't the right place to ask - this is a question rather than an issue and I can't find a more general 'ask a question' type dashing forum?

We're running a Dashing dashboard for live services on a Red Hat VM 2 cpu, 2Gb ram 80G HD. It only has Puppet and Dashing on there. We're wanting to add a second dashboard instance, different port for the development environment. Someone here suggested Dashing or Thin Server might have problems with too many processes/threads on the server and we might need a second VM for it. Having searched it I can't see any known issues, apart from browsers struggling with multiple threads.

As a quick test I've just started a second dashboard instance on our live VM, Nagios says everything is fine. 

Surely a VM of that size can run two or more dashboards without problems?

Thanks in advance.

**Comment by mattrayner** [comment]
Why don't you just make a second dashboard?

We're running a single Dashing instance on a similar box running 4 separate dashboards

**Comment by mattb77** [comment]
Thanks for replying. No, we definitely want a separate instance for live and non live monitoring, separate code base etc. There's 5+ non live environments, the jobs.rb code could be quite different from live and it doesn't matter if I turn the dev monitoring off and on, but live monitoring must be kept up during business hours.

**Comment by mattrayner** [comment]
Running two instances of dashing in daemon mode with different ports should work for you then.

If you set your updates at a recent rate and don't expect too much load on the server then I can't see a problem with your setup. From my testing Dashing seems to be pretty light.

**Comment by mattb77** [comment]
That is helpful. I thought a Linux VM should be able to handle two dashing(s)! Thanks Matt.

**Comment by Panzam** [comment]
Works for me after adding --servers 1 to the command.

cd ${FIRST_DASHING_PATH} && bundle exec dashing start --servers 1 -d -p 8080 -e production -P ${FIRST_DASHING_PTH}/tmp/pids/dashing.pid

cd ${SECOND_DASHING_PATH} && bundle exec dashing start --servers 1 -d -p 8082 -e production -P ${SECOND_DASHINGPATH}/tmp/pids/dashing.pid

Regards,
Mario
