### ISSUE TITLE
Dashing Web Scraper Widget

### ISSUE THREAD

**Issue by rickleigh** [Shopify/dashing#538]
Hello,

I'm trying to add a widget to my dashboard that will scrape our offices total revenue from an intranet page within my company. I want it to scrape every 24 hours and display the results on a widget. There is no API offered or I would have been able to use most available widgets already out there :(

I ran across this bit of coding from http://www.icicletech.com/ that is offered in a tutorial:

require "mechanize"
url = ARGV[0]
fp = File.new("wikilinks.txt", "w")
agent = Mechanize.new { |agent| agent.user_agent_alias = "Mac Safari" }
html = agent.get(url).body
html_doc = Nokogiri::HTML(html)
fp.write("References\n\n")
list = html_doc.xpath("//ol[@class='references']")
list.each { |i| fp.write(i.text + "\n") }
fp.write("Further Reading\n\n")
list = html_doc.xpath("//span[@class='citation']")
list.each { |i| fp.write(i.text + "\n") }

I'm hoping someone would be kind enough to help me convert this or make something simular to meet my needs. I know that this is providing the output to a text file and have some understanding of the code. Here is steps needed to access my data to display:

First to gain access to the page needing scraped, the code will have to apply a user name / submit then provide password/submit. At this point using the URL to the revenue page I would like to scrape and display to widget:

&lt;tfoot &gt;<br />
		&lt;tr &gt;<br />
		&lt;td align='left' class='header_black'&gt;Total<br />
		&lt;/td&gt;<br />
		&lt;td align='right' class='header_black'&gt;$0.00<br />
		&lt;/td&gt;<br />
		&lt;td align='right' class='header_black'&gt;0.0%<br />
		&lt;/td&gt;<br />
		&lt;/tr&gt;<br />
&lt;/tfoot&gt;

Thanks for any guidance on this. I'm really new to coding/Ruby and would like to learn. So I'm not asking for someone to do the work for me but to explain the steps I need to take to get my finished product.

-Rick

**Comment by hpowers** [comment]
check out http://railscasts.com/episodes/190-screen-scraping-with-nokogiri

**Comment by rickleigh** [comment]
Thanks, I'll take a look at it.

**Comment by tylermauthe** [comment]
Any updates on this?

**Comment by rickleigh** [comment]
Nope, can't seem to get anyone to give enough info that I can understand. I've asked here as well:
http://stackoverflow.com/questions/29292643/scraping-a-site-that-requires-login-username-and-password-on-two-separate-pages

**Comment by tylermauthe** [comment]
Thanks for asking your question on SO instead. I will endeavour to answer it there. I intend to write up Issue Submission Guidelines that will require support requests to be submitted there.

Can you please close this issue though? I promise I will connect with you on StackOverflow. :grin:
