### ISSUE TITLE
Number widget: Change rate, arrow and difference not displaying

### ISSUE THREAD

**Issue by howardsternisbatman** [Shopify/dashing#541]
Hello,

I'm using the numbers widget, it updates as expected on a schedule. However the change rate etc. never displays.  I'm sending the data from an excel spreadsheet if that makes any difference.

What am I missing?
number.coffee
![coffee](https://cloud.githubusercontent.com/assets/7604127/6855154/3eb0182c-d3cc-11e4-94c2-28b8c5159f33.PNG)

number.html
![html](https://cloud.githubusercontent.com/assets/7604127/6855117/036f958a-d3cc-11e4-92f7-40b70b2d05be.PNG)

number.scss
![scss](https://cloud.githubusercontent.com/assets/7604127/6855125/11132cba-d3cc-11e4-833a-8efa263bdee5.PNG)

thanks

**Comment by tylermauthe** [comment]
Are you sending the current and last values in your Rufus job?

From the sample project:
```ruby
current_valuation = 0

SCHEDULER.every '2s' do
  last_valuation = current_valuation
  send_event('valuation', { current: current_valuation, last: last_valuation })
end
```

**Comment by howardsternisbatman** [comment]
I found the root of my problem.  I had updated Font-Awesome, 'icon-arrow-up' needed to be changed to 'fa fa-arrow-up'

@tylermauthe thank you for your help.

**Comment by tylermauthe** [comment]
Glad to hear you got it sorted. Hopefully once #514 is merged, people won't have this kind of issue again.
