### ISSUE TITLE
Changing widget background color when @get('change') is > 0

### ISSUE THREAD

**Issue by howardsternisbatman** [Shopify/dashing#545]
I'm hunting and pecking my way through Dashing :-)

I'd like to change the widget background color to #337A35 when the change is > 0 and #dc5945 if it change is less than 0.

I suspect I need to add onData: (data) -> or something but I'm currently lost.

Any pointers?

coffee script

class Dashing.Stock extends Dashing.Widget
  @accessor 'price', Dashing.AnimatedValue

  @accessor 'changepercent', ->
    @get('change')[1..-1] + ' (' + @get('percentchange')[1..-1] + ')'
  
  @accessor 'title', ->
    @get('name') + ' (' +@get('symbol') + ')'
  
  @accessor 'lasttrade', ->
    'Last traded at ' + @get('lasttradetime')
  
  @accessor 'arrow', ->
    if parseFloat(@get('change')) > 0 then 'fa fa-arrow-up' else 'fa fa-arrow-down'

**Comment by tylermauthe** [comment]
Try looking at how the Hotness widget does it:
https://gist.github.com/rowanu/6246149#file-hotness-coffee-L8-L23

**Comment by howardsternisbatman** [comment]
thanks @tylermauthe I will check that out.
