### ISSUE TITLE
data isn't updating

### ISSUE THREAD

**Issue by delfick** [Shopify/dashing#547]
Hello,

I created a dashboard today to try and display how many instances are up in our aws environments.

```ruby
require 'aws-sdk'

def display_env(env, creds)
  ec2 = Aws::EC2::Resource.new(credentials: creds)
  terminated = Proc.new {|instance| instance.state[:name] == "terminated" || instance.state[:name] == "shutting-down" }
  total_num_dead_instances = ec2.instances.select(&terminated).count
  total_num_alive_instances = ec2.instances.reject(&terminated).count

  found = []
  autoscaling = Aws::AutoScaling::Client.new(credentials: creds)
  autoscaling.describe_auto_scaling_groups[:auto_scaling_groups].each do |group|
    name = group[:tags].select {|tag| tag[:key] == "aws:cloudformation:stack-name" }[0][:value]
    desired_capacity = group[:desired_capacity]

    in_service = Proc.new {|instance| instance[:lifecycle_state] == "InService"}
    num_dead_instances = group[:instances].reject(&in_service).count
    num_alive_instances = group[:instances].select(&in_service).count

    found.push({alive: num_alive_instances, dead: num_dead_instances, desired: desired_capacity, name: name })
  end
  puts("#{env} - #{total_num_alive_instances} : #{total_num_dead_instances}")
  send_event("#{env}-env", { dead: total_num_dead_instances, alive: total_num_alive_instances, autoscaling: found })
end

Aws.config.update({region: 'ap-southeast-2'})

unless ENV.fetch("AWS_SECRET_ACCESS_KEY", nil).nil?
  default_creds = Aws::Credentials.new(ENV['AWS_ACCESS_KEY_ID'], ENV['AWS_SECRET_ACCESS_KEY'], ENV['AWS_SECURITY_TOKEN'])
else
  default_creds = Aws::InstanceProfileCredentials.new
end
default_sts = Aws::STS::Client.new({credentials: default_creds})

dev_creds = Aws::AssumeRoleCredentials.new({client: default_sts, role_arn:'arn:aws:iam::<<my-dev-account-id>>:role/dashing/viewer', role_session_name: 'dashing'})
stg_creds = Aws::AssumeRoleCredentials.new({client: default_sts, role_arn:'arn:aws:iam::<<my-stg-account-id>>:role/dashing/viewer', role_session_name: 'dashing'})
prod_creds = Aws::AssumeRoleCredentials.new({client: default_sts, role_arn:'arn:aws:iam::<<my-prod-account-id>>:role/dashing/viewer', role_session_name: 'dashing'})

SCHEDULER.every '1m' do
  display_env(:dev, dev_creds)
  display_env(:stg, stg_creds)
  display_env(:prod, prod_creds)
end
```

This seems to work fine and creates the values I expect. The puts there also puts out the correct values each time.

However, it seems the events that are sent to the server never change value and the value in history.yml never change value.

I get no errors in either the browser or the logs.

I'm using dashing 1.3.4

I'm not sure how to further debug this problem....

Thanks

Stephen.

**Comment by tylermauthe** [comment]
Try loading /events in your browser and watch the event stream for a bit. Are the JSON values coming through as you expect?

**Comment by delfick** [comment]
Nup. When I trace the events they come in as old values. The only thing
that makes them update is stopping and starting dashing.

**Comment by tylermauthe** [comment]
Do you have other jobs that are sending data successfully?

**Comment by delfick** [comment]
It would appear the default jobs are suffering from the same problem.

**Comment by tylermauthe** [comment]
What if you create a new project? Does that work?

**Comment by tylermauthe** [comment]
If you are able to run the demo project:

Are you running Dashing with `dashing start`? If so, do you have any customisation in your `config.ru`?

You can try deleting your `history.yml` and ensuring the directory is writable by the user that is executing Dashing.

Alternatively, create a new project and copy your jobs, dashboards and any custom widgets into the new directory.

**Comment by delfick** [comment]
I compared to a new project and nothing really changes other than the new jobs and dashboards.

it does seem however that you've given me the answer.

I had a setup using unicorn instead of calling dashing start.

It would appear that if I call dashing start then the default jobs atleast are updating values.

I shall change my deployment.

Thankyou.

Stephen.

**Comment by tylermauthe** [comment]
You should be able to use unicorn. Add it to your `Gemfile` and reinstall your bundle with `bundle install` and then run unicorn from the bundle with `bundle exec unicorn`.

**Comment by delfick** [comment]
it would appear unicorn's "preload_app true" option is causing the data to
be stale.

If I remove that option then the data refreshes :)
