### ISSUE TITLE
Not seeing any data in my dashboard

### ISSUE THREAD

**Issue by trekr5** [Shopify/dashing#553]
Hi,

I have a sample (default) dashboard and a number widget on my vagrant Ubuntu box.

It worked for a while and then stopped. When I look at /events, through the browser, there isn't any data being sent through. I have destroyed my vagrant box and rebuilt it but all to no avail. However when I stop the dashing server, I suddenly see data coming through to my widgets!

I have currently set my scheduler in my number widget to a minute and then also included sleep 60 in my code to give adequate time for /events to fire but nothing has happened.

I'm very stuck and would really appreciate pointers on how to solve this problem.

I'm viewing my widgets through a Firefox browser and a Chrome browser.

Thanks

**Comment by trekr5** [comment]
Solved it!

There was a problem whereby the :3030 port on my vagrant machine was stuck in waiting mode. I did a vagrant reload and the ports were freed and I immediately saw data flowing through.

**Comment by R2Developer** [comment]
i am using windows, do i know how to check the port ? facing same problem..pls help
