### ISSUE TITLE
Get content of a widget?

### ISSUE THREAD

**Issue by crashmaster** [Shopify/dashing#559]
Is there a way to get the content of a single widget (in JSON)?

**Comment by pushmatrix** [comment]
There currently isn't, but that's a pretty good idea and I'll look into adding it.

In the meantime, there is a workaround. Inside your `config.ru` file, paste the following inside the `configure do....end` block:
```ruby
get '/widgets/:id.json' do
  content_type :json
  if data = settings.history[params[:id]]
    data.split[1]
  end
end
```

You should then be able to go to /widgets/your_widget_name.json to get the most recent data :)
