### ISSUE TITLE
http response after POST

### ISSUE THREAD

**Issue by catalinabustam** [Shopify/dashing#566]
Hi,
 When I send a feature through the Http Post, the widget get the correct update, but it does not send any response,  so the application that send the post detect it as a "Error connecting to HTTP server" 
Thanks

**Comment by tylermauthe** [comment]
I have a widget which submits data via HTTP POST, triggered by JavaScript in the user's browser -- it works fine for me.

How are you sending the request and what kind of response are you expecting back?

This is the response header that my jQuery.post happily accepts, resolving the Deferred:
```
HTTP/1.1 204 No Content
Date: Wed, 20 May 2015 00:43:35 GMT
Server: thin
X-Content-Type-Options: nosniff
Content-Length: 0
Connection: close
Content-Type: text/plain; charset=UTF-8
```

**Comment by pushmatrix** [comment]
Like @tylermauthe said, you should be receiving 204's:

https://github.com/Shopify/dashing/blob/master/lib/dashing/app.rb#L108

**Comment by catalinabustam** [comment]
When I put a wrong auth_token, I receive the 404 status but when I send the correct one, the widget gets the update but my application (Mirth Connect) say failed, it could be possible that it is expecting a status 204 like the status 404 on failure.

**Comment by tylermauthe** [comment]
If this application thinks that a 204 means failure, it is not interpreting HTTP correctly. Please submit a support request to them, this is not an issue with Dashing.

Thank you and good luck with your issue.
