### ISSUE TITLE
What is the order of events?

### ISSUE THREAD

**Issue by contentfree** [Shopify/dashing#571]
I'm trying to figure out where "do once" initialization code should go for a widget. Intuitively, I thought that ready would fire before onData. However, it seems that we're regularly seeing onData before ready?

Is there a documented order somewhere? Is it: constructor, onData, ready, onData, onData … onData?

**Comment by tylermauthe** [comment]
In short, there isn't a pre-defined order. I suggest trying to implement your widget in such a way that it doesn't matter what order the events occur. For example, the Graph widget will only process the onData event if the `@graph` is initialised: https://github.com/Shopify/dashing/blob/439182f3b91c6c3c0cb5b5c8f5bee2562cfff2d4/templates/project/widgets/graph/graph.coffee#L35.

If this is unreasonable or impossible, I suggest using a `jQuery.Deferred` to synchronise the asynchronous events.

Something like (untested):
```coffeescript
...
libraryLoading: $.Deferred()
ready:
  @loadUpMyLibs();
  // call this when all init completed (might need to go in callback if lib init is async.)
  @libraryLoading.resolve();
onData:
  @deferred.done(@doMyStuff);
doMyStuff:
  // some stuff
...
```

To elaborate a bit on why there is no order...

`onData` is fired when there is a message received from the SSE EventSource: https://github.com/Shopify/dashing/blob/439182f3b91c6c3c0cb5b5c8f5bee2562cfff2d4/javascripts/dashing.coffee#L107-L115

`ready` is fired when the Batman.js view is 'ready': https://github.com/Shopify/dashing/blob/439182f3b91c6c3c0cb5b5c8f5bee2562cfff2d4/javascripts/dashing.coffee#L55-L56

A Batman.js view is considered ready when "the view's bindings have been initialized. The view may or may not be in the DOM." (http://batmanjs.org/docs/api/batman.view_lifecycle.html#ready)

**Comment by contentfree** [comment]
Thanks. I did end up going with something similar. (Should your `@deferred.done` been `@libraryLoading.done`?)

**Comment by tylermauthe** [comment]
Yeah, I had initially called it `@deferred` but decided `@libraryLoading` was a better name. Glad you were able to resolve your issue and thanks for closing this.
