### ISSUE TITLE
Future of Batmanjs

### ISSUE THREAD

**Issue by newcron** [Shopify/dashing#584]
Hi Guys, 
Given that batman.js was abandoned - are there any alternatives planned for views in dashing? 
Although a bit different in architecture, mustache.js could work out just fine.

**Comment by tylermauthe** [comment]
Duplicate of #498.

mustache.js is not an adequate substitute for batman.

**Comment by tylermauthe** [comment]
Duplicate of #592 ... :trollface:

**Comment by thelinuxlich** [comment]
I took a stab on this but using Node.js and Vue: https://github.com/thelinuxlich/vue-dashing-js

**Comment by Guillaumichaud** [comment]
Why not closing this issue as it is a duplicate of #498?
