### ISSUE TITLE
Thor 0.19.0

### ISSUE THREAD

**Issue by ball-hayden** [Shopify/dashing#588]
Please relax your gemspec to allow thor '0.19.0'

I am attempting to use dashing with https://github.com/google/google-api-ruby-client version 0.9.pre1, which requires `thor, '~> 0.19'`.

I have forked dashing and relaxed this myself, and haven't seen any issues.

**Comment by tylermauthe** [comment]
Feel free to submit that fork as a pull request. Based on the way it is used in Dashing core, I don't upgrading it being an issue.
