### ISSUE TITLE
crash when running "dashing start"

### ISSUE THREAD

**Issue by tbaror** [Shopify/dashing#591]
Hi,
I Installed Dashing on Ubuntu 14.04.2 x64 all went seems to but now when  i am running
"dashing start " i get following error below 
any idea how to fix it 
please advice 
Thanks 
root@mon:~/dalet_dashboard# dashing start
/var/lib/gems/1.9.1/gems/execjs-2.0.2/lib/execjs/runtimes.rb:51:in `autodetect': Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of ava                      ilable runtimes. (ExecJS::RuntimeUnavailable)
        from /var/lib/gems/1.9.1/gems/execjs-2.0.2/lib/execjs.rb:5:in `<module:ExecJS>'
        from /var/lib/gems/1.9.1/gems/execjs-2.0.2/lib/execjs.rb:4:in `<top (required)>'
        from /var/lib/gems/1.9.1/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require'
        from /var/lib/gems/1.9.1/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /var/lib/gems/1.9.1/gems/coffee-script-2.2.0/lib/coffee_script.rb:1:in `<top (required)>'
        from /var/lib/gems/1.9.1/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require'
        from /var/lib/gems/1.9.1/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /var/lib/gems/1.9.1/gems/coffee-script-2.2.0/lib/coffee-script.rb:1:in `<top (required)>'
        from /var/lib/gems/1.9.1/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require'
        from /var/lib/gems/1.9.1/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:5:in `<top (required)>'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing.rb:3:in `require'
        from /var/lib/gems/1.9.1/gems/dashing-1.3.4/lib/dashing.rb:3:in `<top (required)>'
        from config.ru:1:in `require'
        from config.ru:1:in `block in <main>'
        from /var/lib/gems/1.9.1/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
        from /var/lib/gems/1.9.1/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `eval'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `load'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:72:in `start'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
        from /var/lib/gems/1.9.1/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
        from /usr/local/bin/thin:23:in `load'
        from /usr/local/bin/thin:23:in `<main>'

**Comment by r0n22** [comment]
You do not have a javascript runtime installed.  So you would be wanting to install nodejs or alternative to fix this.
```
sudo apt-get install nodejs
```

**Comment by tbaror** [comment]
thanks works
