### ISSUE TITLE
Dashing Workshop - Can't Make Widgets Load

### ISSUE THREAD

**Issue by JaiAslam** [Shopify/dashing#596]
I've followed all the directions up until the point in part 3 when it asks me to use cURL. At which point I get the error invalid API key. I've got a dashboard up and running but I simply can't get the widgets to display. I copied all the code verbatim from this link:

https://github.com/Shopify/dashing/wiki/Dashing-Workshop

Anybody have any thoughts on what's going wrong?

**Comment by JaiAslam** [comment]
So I figured out the issue was simply that I didn't have Node.JS installed so that's why my widgets weren't displaying at all. Now they are displaying and I'm no longer getting the invalid API key error.

**Comment by pushmatrix** [comment]
Strange, you shouldn't need to have node.js installed for this to work. Glad you got it working though.

**Comment by tylermauthe** [comment]
If your OS doesn't have a JS Script Host then you may need to install one. Windows and OSX both have em.

This is a fairly common source of trouble for newcomers to Dashing. If we included `therubyracer` in the default Gemfile for the template project, it would eliminate this problem -- but we wouldn't always be using your OS's native JS host. We would instead use the native V8 engine bundled with the gem.
