### ISSUE TITLE
Feature Request:  Fullscreen Mode

### ISSUE THREAD

**Issue by BillyBarbaro** [Shopify/dashing#599]
I'm working on a dashboard to display in my office, and I'd like to run fullscreen so the address bar disappears, like when you watch a YouTube video in fullscreen.  It's also nicely implemented in another beautiful looking open source project, reveal.js.  You can take a look at it here: http://lab.hakim.se/reveal-js.  After the page loads, press the f key to launch the web app in fullscreen.

Using that as a template, I've played around and added that functionality to dashing.  It works great for my needs.  The only downside I could find is that it disables scrolling.  Although I foresee most people using a presentation mode for "view-only" dashboards, so I'm not sure that will be an issue.

If you think it would be a worthwhile addition to the project, please let me know, and I'll fork the repo and add my changes so you can take a look at what I've done.

**Comment by pushmatrix** [comment]
Hey this sounds like a great idea. I do agree that most people using it don't use scrolling.

However many run dashing off of raspberry PIs and dedicated boxes, which may not have access to press 'f' for fullscreenage.

**Comment by tylermauthe** [comment]
This doesn't feel like it should be part of Dashing core, I'm not sure though. Chrome already supports this by entering "Presentation Mode" (under the View menu on OSX).

I would suggest to implement this as a Widget instead. The widget wouldn't take up any space, but when added to a dashboard it would simply enter fullscreen mode when the page loads (no need to hit F).

**Comment by BillyBarbaro** [comment]
That's a good concern @pushmatrix.  Do you have any thoughts on how we could solve that?  I've done a little reading on the Fullscreen API, and it appears it can only be triggered by "user interaction task source."  Which means by a click, keypress, or other user action.

While Chrome does have a presentation view, I prefer to use either Firefox or Safari, neither of which have a native presentation mode (although I know there are Firefox plugins available, but it would be more convenient if the feature were just within the framework).  I thought the widget idea was intriguing, but that would violate the Fullscreen API Standard.

I'll give some more thought to how it could work on a raspberry pi.  Any chance someone could point me toward some code that demonstrates how it would be run on a pi?  I'm not quite familiar with it.  It seems like there's enough interest to at least get the code up though.  When I get the chance in the next day or two, I'll go ahead and fork the repo and push up my changes.

**Comment by tylermauthe** [comment]
I think what @pushmatrix is getting at is that Dashing is often run without a keyboard / mouse. So if you require user interaction, I don't think this fits into Dashing core.

I went ahead and made the widget:
https://gist.github.com/tylermauthe/75e70a7bc4ae7c237453

Bam! Feel free to leave feedback for the widget on that Gist.

**Comment by BillyBarbaro** [comment]
I've been using the widget for a while now.  Seems to work fine for me.  Thanks for the help!  You saved me a little bit of work.  I'll go ahead and close the issue.
