### ISSUE TITLE
Anyone done anything with Google DFP (not Ads) ?

### ISSUE THREAD

**Issue by derwin12** [Shopify/dashing#601]
Wondering what might be out there that google search isnt showing...

**Comment by pushmatrix** [comment]
I assume you're talking about a widget based on showing DFP?

**Comment by tylermauthe** [comment]
People are supposed to add their widgets to this list:
https://github.com/Shopify/dashing/wiki/Additional-Widgets

I don't see one in the list. Feel free to create one.
