### ISSUE TITLE
Cycling through Dashboards by using Hotkeys

### ISSUE THREAD

**Issue by zwergengott** [Shopify/dashing#622]
Hi,
i was starting to make a dashboard for my company with cycling widgets and multiple dashboards - everything works fine so far. But now my collegues want a functionality to scroll through the boards by using a key pad thats next to the TV in order to see the informations they want quicker. 

Did anybody do this already or has an idea how to achieve this?

**Comment by VAdamec** [comment]
What about to use multiple tabs and something like Firefox tab rotator or key shortcuts to walk through multiple dashboards ?
