### ISSUE TITLE
Add a new Sinatra endpoint?

### ISSUE THREAD

**Issue by rmangino** [Shopify/dashing#629]
Hi,

Is there an easy way to add a new Sinatra endpoint?

I'd like to incorporate a [Dropbox webhook](https://www.dropbox.com/developers-v1/webhooks/docs) so that I can update a widget whenever a certain file changes in Dropbox. For that to work I have to add a new endpoint (e.g. https://www.example.com/dropbox-webhook) to the dashing server.

Any advice would be much appreciated!

**Comment by pushmatrix** [comment]
Check out the documentation on how to add authentication, and it includeds adding in some endpoints.
https://github.com/Shopify/dashing/wiki/How-to:-Add-authentication

**Comment by rmangino** [comment]
Thank you @pushmatrix !
