### ISSUE TITLE
Looking Job Examples.

### ISSUE THREAD

**Issue by BassieZ** [Shopify/dashing#634]
Using Dashing now to create some fancy dashboards. Have the number, Hotness and List widget working now but can anyone send me a job example for the Meter and Graph Widget? 

The SQL query returns a single value like "95" so the meter widget must show 95%.

**Comment by MartynKeigher** [comment]
Hey buddy, 

Here is what I have for a meter widget...

jobs/count.rb
```
require_relative 'my_db.rb'

SCHEDULER.every '10m', :first_in => 0 do |job|

        db = MyDb.conn

        sql = "SELECT `name` FROM `table` WHERE `column` = foo"

        results = db.query(sql)

        current_count = results.count


        send_event('count', { value: current_count } )
db.close
end
```

dashboards/home.erb
```
<li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="count" data-view="Meter" data-title="ESET Installs" data-min="0" data-max="500"></div>
    </li>
```

Hope this helps you out! (I don't use the graph, so hopefully someone else can share an example!) 

Regards, 

://mk

**Comment by BassieZ** [comment]
Hi Martyn,

What a surprise to get an answer from you here. Thanks for the quick reply!
So, now I know your familiar with Labtech too, this can help to get this done.

My Query is created to get a health value for one particular customer:
SELECT IFNULL(ROUND((SUM(healthscore)/COUNT(*))*10),0) as 'total' FROM plugin_sap_latesthealthresults

So as you can see, the output is a number, not a bunch of rows. Problem is in your example, the job require a bunch of rows and will count them (current_lollipops = results.count)

So what i need to reach is the output of this query translated to "lollipops".

Does it makes any sense?

Bas

**Comment by MartynKeigher** [comment]
Hi Bas!

Let me know if this works...

<b>jobs/clienthealthscore</b>

```
require_relative 'my_db'

SCHEDULER.every '120m', :first_in => 0 do |job|

        db = MyDb.conn

        sql = "SELECT IFNULL(ROUND((SUM(healthscore)/COUNT())10),0) as 'total' FROM plugin_sap_latesthealthresults"

        results = db.query(sql)

        current_healthscore = object.each

        send_event('healthscore', { value: current_healthscore } )
db.close
end
```

Regards,

://mk

**Comment by BassieZ** [comment]
Hi Martyn,

LabTech is a great tool for spreading virusses in a managed and controlled way ;-)

However, the above solution doesn't work. The query in my case returns a value of 93. However, it shows "1" in the meter widget. Also tried to use results.echt instead of object.each but that returns a "[object]" value in the widget so no good at all.
Got any other ideas?

Bas

**Comment by MartynKeigher** [comment]
Hey @BassieZ,

Sorry for the UBER-delayed repsonse!! I hope you already have this working!!

If not, then try this out... (Simple example, but you should be able to see what I'm doing there!)

```
require_relative 'my_db.rb'

SCHEDULER.every '5s', :first_in => 0 do |job|
     db = MyDb.conn

     sql = "SELECT COUNT(*) AS 'count' FROM computers;"

     results = db.query(sql).first

     current_agentcount = results['count']

     send_event('agentcount', { value: current_agentcount } )
db.close
end
```

://mk

**Comment by BassieZ** [comment]
Hi Martyn,

It was worth waiting for!! It works! Got a beautifull meter widget now. Thanks a million

Bas

**Comment by abhin123** [comment]
I want to push numeric data from a file to my dashboard.

I am using the following .rb file as job for pushing the data

SCHEDULER.every '30s' do
var = File.open("/dashing/abhi/sample.txt", "r")
var.each_line do |line|
    puts line
send_event('polarion', { value: var })
end
end
but the data is not being displayed in dashboard. THe content of /dashing/abhi/sample.txt is a number.

cat /dashing/abhi/sample.txt
54
