### ISSUE TITLE
Can't install gem on El Capitan

### ISSUE THREAD

**Issue by ArielCabib** [Shopify/dashing#636]
$gem install dashing

    Building native extensions.  This could take a while...
    ERROR:  Error installing dashing:
    	ERROR: Failed to build gem native extension.

        /Users/ariel/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20151112-935-6qmv8h.rb extconf.rb
    checking for rb_trap_immediate in ruby.h,rubysig.h... no
    checking for rb_thread_blocking_region()... no
    checking for ruby/thread.h... yes
    checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
    checking for inotify_init() in sys/inotify.h... no
    checking for __NR_inotify_init in sys/syscall.h... no
    checking for writev() in sys/uio.h... yes
    checking for rb_thread_fd_select()... yes
    checking for rb_fdset_t in ruby/intern.h... yes
    checking for pipe2() in unistd.h... no
    checking for accept4() in sys/socket.h... no
    checking for SOCK_CLOEXEC in sys/socket.h... no
    checking for rb_wait_for_single_fd()... yes
    checking for rb_enable_interrupt()... no
    checking for rb_time_new()... yes
    checking for sys/event.h... yes
    checking for sys/queue.h... yes
    CFLAGS=-O3 -I/Users/haven/.sm/pkg/active/include -fPIC -mmacosx-version-min=10.7 -pipe  -Wall -Wextra -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-unused-result
    CPPFLAGS=-D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT $(DEFS) $(cppflags) -Wall -Wextra -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-unused-result
    checking for clock_gettime()... no
    checking for gethrtime()... no
    creating Makefile

    make "DESTDIR=" clean

    make "DESTDIR="
    compiling binder.cpp
    In file included from binder.cpp:20:
    ./project.h:116:10: fatal error: 'openssl/ssl.h' file not found
    #include <openssl/ssl.h>
             ^
    1 error generated.
    make: *** [binder.o] Error 1

    make failed, exit code 2

    Gem files will remain installed in /Users/ariel/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.8 for inspection.
    Results logged to /Users/ariel/.rvm/gems/ruby-2.2.1/extensions/x86_64-darwin-14/2.2.0-static/eventmachine-1.0.8/gem_make.out

Might be related to this https://github.com/phusion/passenger/issues/1630 ?

**Comment by pushmatrix** [comment]
Looks like this is affecting other gems too. It seems to deal with El Capitain no longer coming with OpenSSL headers. See if the fixes here work for you: https://github.com/eventmachine/eventmachine/issues/643

**Comment by ArielCabib** [comment]
That solved it. Thanks.

**Comment by kovacshuni** [comment]
+1
