### ISSUE TITLE
Can I load index.html if no dashboard is requested?

### ISSUE THREAD

**Issue by derwin12** [Shopify/dashing#642]
Can the confug.ru &  "default_dashboard" be coded such that it loads index.html instead of a dashboard erb file?

**Comment by JermilaPaulDhas** [comment]
Have your index.html within the dashboards directory.
And in the config.ru file, set the parameter :default_dashboard to 'index'.

And restart dashing. And it should render the index.html page.

**Comment by derwin12** [comment]
That is perfect. Thanks.
