### ISSUE TITLE
Small clock widget issue

### ISSUE THREAD

**Issue by dieterdemeyer** [Shopify/dashing#65]
I've noticed that the dimensions of the clock widget don't match with the standard dimensions for other widgets that span only 1 column and 1 row.
I have tried to decrease the size of the font in the clock widget but without any luck..

Could you perhaps give me some pointers on how I could fix this ?

Thank you.

**Comment by contentfree** [comment]
@pushmatrix Did you ever figure out the 1 pixel gap for widgets that have an icon background? I'm seeing it still in the latest Chrome.

**Comment by contentfree** [comment]
@pushmatrix Simply flipping the order of icon and widget content ala the following fixes the 1 pixel gap:

````
    <li data-row="1" data-col="1" data-sizex="6" data-sizey="4">
      <i class="icon-time icon-background"></i>
      <div data-view="Clock"></div>
    </li>
````
vs
````
    <li data-row="1" data-col="1" data-sizex="6" data-sizey="4">
      <div data-view="Clock"></div>
      <i class="icon-time icon-background"></i>
    </li>
