### ISSUE TITLE
Prevent Click after Drag

### ISSUE THREAD

**Issue by Gugiman** [Shopify/dashing#651]
Somebody got the same problem as me?

The tile is completely clickable. Now i drag a tile to another field and after dropping it the event of the tile is triggered.

How to drag a tile without clicking at the end?

**Comment by DeanCording** [comment]
The solution I have used to prevent this is to add a drag handle to the widget.

In the dashboard file, add a `<header>` for every widget, for example:

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
        <header class="fa fa-arrows drag-handle"></header>
        <div data-id="time" data-view="Clock"></div>
    </li>

We just need to tell gridster about the handle, using `handle: 'header'` in assets/javascript/application.coffee:

      Batman.setImmediate ->
        $('.gridster').width(contentWidth)
        $('.gridster ul:first').gridster
          max_size_x: Dashing.numColumns
          widget_margins: Dashing.widget_margins
          widget_base_dimensions: Dashing.widget_base_dimensions
          avoid_overlapped_widgets: !Dashing.customGridsterLayout
          draggable:
            stop: Dashing.showGridsterInstructions
            start: -> Dashing.currentWidgetPositions = Dashing.getWidgetPositions()
            handle: 'header'
   

Now for some CSS magic to make the handle appear and disappear on mouse over.  In assets/stylesheets/application.scss add:

    .drag-handle {
      position: absolute;
      right: 5px;
      top: 5px;
      opacity: 0;
    }

    .drag-handle:hover {
      opacity: 1;
    }
