### ISSUE TITLE
Dashing + win32-service

### ISSUE THREAD

**Issue by m-baumgartner** [Shopify/dashing#668]
I'd like to run my dashing board as a windows service.
I came across `win32-service` (https://github.com/djberg96/win32-service) that seems to be doing what I want since Dashing is a ruby app.
Howerver win32-service needs a `.rb` file path apparently. 
Has anyone ever done that? How should I proceed?

Thanks

**Comment by somehuman** [comment]
After many trials and errors, I run Dashing as a windows service using NSSM (Non-Sucking Service Manager which is fantastic and is freely available on the web) and have really had no problems with Dashing running as a service.

Make sure you use either the 32 or 64 bit version of NSSM as appropriate. The settings I use for NSSM to run Dashing are: (obviously yours would be different)

Path: C:\RailsInstaller\Ruby2.0.0\bin\ruby.exe
Startup directory: C:\MyDashboard
Arguments:  C:\RailsInstaller\Ruby2.0.0\bin\thin start -p 3030

Hope this helps...

SomeHuman

**Comment by m-baumgartner** [comment]
Working like a charm Thank you!
Obviously my parameters were different yes but i'd like to give a little advice to anyone going around here

instead of starting `thin` with 
[ruby bin path]\thin start -p 3030
you can start directly dashing with 
[ruby bin path]\dashing start

Since the startup directory is your dashboard master folder it contains everything you need to work

**Comment by m-baumgartner** [comment]
NB : I kinda made it work with a simple `sc screate` too but it seems less stable than using NSSM.
