### ISSUE TITLE
Twitter Accounts (Showing timeline)

### ISSUE THREAD

**Issue by MartynKeigher** [Shopify/dashing#669]
Hey all, 

Has anyone updated the existing masters' `twitter.rb` file to allow tweets to display using the updated Twitter API?? If you install and run your dash from the master, today... the current twitter config wont work. 

Can anyone point me in the direction of a/their gist?

Thanks.

://mk.

**Comment by pushmatrix** [comment]
Ah damn, didn't realize they changed it. If you figure out what's changed it'd be great to get that merged in.

**Comment by MartynKeigher** [comment]
Hey Daniel! For sure man... I'm working on it!! 

Will let you know when/if I get it going! :)

**Comment by pushmatrix** [comment]
Thanks @MartynKeigher!
