### ISSUE TITLE
dashing start throwing errors

### ISSUE THREAD

**Issue by brijesh27** [Shopify/dashing#686]
Hi,
I have install ruby 2.1 with rvm,  but while starting dashing throwing below errors, please  let me know how to fix this. 

[root@localhost monitorama]# dashing start
/usr/local/rvm/gems/ruby-2.1.0/gems/execjs-2.0.2/lib/execjs/runtimes.rb:51:in `autodetect': Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
	from /usr/local/rvm/gems/ruby-2.1.0/gems/execjs-2.0.2/lib/execjs.rb:5:in `<module:ExecJS>'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/execjs-2.0.2/lib/execjs.rb:4:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/coffee-script-2.2.0/lib/coffee_script.rb:1:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/coffee-script-2.2.0/lib/coffee-script.rb:1:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/dashing-1.3.4/lib/dashing/app.rb:5:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/dashing-1.3.4/lib/dashing.rb:3:in `require'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/dashing-1.3.4/lib/dashing.rb:3:in `<top (required)>'
	from config.ru:1:in `require'
	from config.ru:1:in `block in <main>'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
	from /usr/local/rvm/gems/ruby-2.1.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.0/bin/thin:22:in `load'
	from /usr/local/rvm/gems/ruby-2.1.0/bin/thin:22:in `<main>'
	from /usr/local/rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by tylermauthe** [comment]
You need a JavaScript runtime of some sort, probably just install NodeJS. therubyracer gem is another option to look into.

Previous answer: https://github.com/Shopify/dashing/issues/20

**Comment by brijesh27** [comment]
thx working fine now
