### ISSUE TITLE
Default Twitter Widget "undefined"

### ISSUE THREAD

**Issue by moosemedia** [Shopify/dashing#703]
I have made no changes to the code and the sample will not find  #todayilearned after I have added the appropriate keys. There is not error when the job is run.

**Comment by n3rdz** [comment]
i got it to work when i change the job file like this


end
  search_term = URI::encode('#todayilearned')
    SCHEDULER.every '1m', :first_in => 0 do |job|
        begin
          tweets = twitter.search("#{search_term}")
          if tweets
          tweets = tweets.map do |tweet|
        { name: tweet.user.name, body: tweet.text, avatar: tweet.user.profile_image_url_https }
      end
      send_event('twitter_mentions', comments: tweets)
    end
  rescue Twitter::Error
    puts "\e[33mFor the twitter widget to work, you need to put in your twitter API keys in the jobs/twitter.rb file.\e[0m"
  end
end

**Comment by moosemedia** [comment]
I have copied your code and it still isnt working for me

**Comment by n3rdz** [comment]
i uploaded all the related files
i hope it helps

https://drive.google.com/folderview?id=0B7w5-DRaKIS-djNqR2wxWlZsSDQ&usp=sharing

ps: i changed the dataview from comments to tweets

**Comment by moosemedia** [comment]
Awesome that worked! thanks
