### ISSUE TITLE
Adding a dashboard to existing rails app?

### ISSUE THREAD

**Issue by tamooch** [Shopify/dashing#709]
I have a rails app I've been developing on the Cloud 9 IDE. I've been looking for the best solution for a user dashboard once someone authenticates to Devise. Dashing looks awesome. 

How do I install the gem and create a new dashboard, without having to create a whole new rails project? I can't have two apps running in the same c9 workspace, so I need to create a new dashboard in my existing application so I can connect to my db, etc... right? 

Thanks for any help.

**Comment by pushmatrix** [comment]
Hmm, not sure I can be of much help because this project doesn't rely on Rails at all. It's a Sinatra app.

Maybe the folks over at dashing-rails can be of help: https://github.com/gottfrois/dashing-rails
