### ISSUE TITLE
Dashing not working properly

### ISSUE THREAD

**Issue by shenbaga2016** [Shopify/dashing#721]
Hi,

I installed RailsInstaller and created a new dashing project.
While testing the "My super sweet dashboard" I get black screen with the below content only.
Try this: curl -d '{ "auth_token": "YOUR_AUTH_TOKEN", "text": "Hey, Look what I can do!" }' \http://localhost:3030/widgets/welcome
[Dashing Issue.docx](https://github.com/Shopify/dashing/files/464907/Dashing.Issue.docx)

**Comment by Litwilly** [comment]
What browser are you using? I.E. is not supported.

**Comment by Litwilly** [comment]
Looks like your using Internet explorer, try chrome or firefox. Dashing utilizes websockets which is not supported by internet explorer.

**Comment by shenbaga2016** [comment]
I check with Chrome as well and I am getting the same black screen with that content.

**Comment by shenbaga2016** [comment]
After installing Node.js this issue gets resolved.
