### ISSUE TITLE
cURL / dashing problems

### ISSUE THREAD

**Issue by laksdjfhlkajsfh23** [Shopify/dashing#729]
Hi,

I'm very new to ruby and all but i installed dashing and i want to communicate with the widgets using curl.
But if I try to execute a cURL command in the cmd there is always this error:
curl: (6) Could not resolve host: 'auth_token'
curl: (6) Could not resolve host: 'test',
curl: (6) Could not resolve host: 'message'
curl: (6) Could not resolve host: 'Hey,
curl: (6) Could not resolve host: Look
curl: (6) Could not resolve host: what

and I want to ask what I'm doing wrong or how I have to fill the syntax for the cURL commands.

Can you help me please?

thanks

**Comment by litwi1rm** [comment]
What command are you trying? Did you enter your auth token? You can find or change your auth code in config.ru file.

**Comment by laksdjfhlkajsfh23** [comment]
curl -d '{ "auth_token": "[AUTH_TOKEN]", "message": "Hey, Look what I can do!", "type": "alarm"}' http://localhost:3030/widgets/shoutbox I used this command and I put my auth token in the "" of "[AUTH_TOKEN]"

**Comment by litwi1rm** [comment]
what environment are you trying to send the curl from?

**Comment by litwi1rm** [comment]
if its windows try this instead:

curl -X POST  -H "Content-Type: application/json" -d "{ \"auth_token\": \"YOUR_AUTH_TOKEN\", \"message\": \"Hey, Look what I can do!\",\"type\":\"alarm\" }" http://localhost:3030/widgets/shoutbox

**Comment by laksdjfhlkajsfh23** [comment]
Thanks a lot it works fine now!
