### ISSUE TITLE
Link to gridster dot net is malicious

### ISSUE THREAD

**Issue by jundis** [Shopify/dashing#731]
The link on the dashing.io homepage to gridster dot net leads to a malicious website.

This link can be found under the "Laying out the widgets" subsection of "Example Dashboard"

"Dashing uses >>gridster.js<< to create a layout for your widgets. Each widget is part of an unordered list. The \<li> element for a widget contains:"

Suggestion: Remove link or change to https://github.com/dsmorse/gridster.js or one of the other forks of the original gridster.

**Comment by pushmatrix** [comment]
Oh shit, that's not good. Fixed!
Thanks for bringing that up.
