### ISSUE TITLE
cannot load such file -- json (LoadError)

### ISSUE THREAD

**Issue by jirah** [Shopify/dashing#89]
Hi,

I'm installing dashing on my Fedora 17 Desktop, and the demo project (sweet_dashboard_project) dosn't start.

**[ricardo@iridium sweet_dashboard_project]$ dashing start**
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
/home/ricardo/.gem/ruby/1.9.1/gems/backports-3.1.1/lib/backports/tools.rb:328:in `require': cannot load such file -- json (LoadError)
    from /home/ricardo/.gem/ruby/1.9.1/gems/backports-3.1.1/lib/backports/tools.rb:328:in`require_with_backports'
    from /home/ricardo/.gem/ruby/1.9.1/gems/dashing-1.0.4/lib/dashing.rb:7:in `<top (required)>'
    from config.ru:1:in`require'
    from config.ru:1:in `block in <main>'
    from /home/ricardo/.gem/ruby/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in`instance_eval'
    from /home/ricardo/.gem/ruby/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
    from config.ru:1:in`new'
    from config.ru:1:in `<main>'
    from /home/ricardo/.gem/ruby/1.9.1/gems/thin-1.5.1/lib/rack/adapter/loader.rb:33:in`eval'
    from /home/ricardo/.gem/ruby/1.9.1/gems/thin-1.5.1/lib/rack/adapter/loader.rb:33:in `load'
    from /home/ricardo/.gem/ruby/1.9.1/gems/thin-1.5.1/lib/thin/controllers/controller.rb:181:in`load_rackup_config'
    from /home/ricardo/.gem/ruby/1.9.1/gems/thin-1.5.1/lib/thin/controllers/controller.rb:71:in `start'
    from /home/ricardo/.gem/ruby/1.9.1/gems/thin-1.5.1/lib/thin/runner.rb:187:in`run_command'
    from /home/ricardo/.gem/ruby/1.9.1/gems/thin-1.5.1/lib/thin/runner.rb:152:in `run!'
    from /home/ricardo/.gem/ruby/1.9.1/gems/thin-1.5.1/bin/thin:6:in`<top (required)>'
    from /home/ricardo/bin/thin:23:in `load'
    from /home/ricardo/bin/thin:23:in`<main>'
[ricardo@iridium sweet_dashboard_project]$ dashing start
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
/home/ricardo/.gem/ruby/1.9.1/gems/backports-3.1.1/lib/backports/tools.rb:328:in `require': cannot load such file -- json (LoadError)
    from /home/ricardo/.gem/ruby/1.9.1/gems/backports-3.1.1/lib/backports/tools.rb:328:in`require_with_backports'
    from /home/ricardo/.gem/ruby/1.9.1/gems/dashing-1.0.4/lib/dashing.rb:7:in `<top (required)>'
    from config.ru:1:in`require'
    from config.ru:1:in `block in <main>'
    from /home/ricardo/.gem/ruby/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in`instance_eval'
    from /home/ricardo/.gem/ruby/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
    from config.ru:1:in`new'
    from config.ru:1:in `<main>'
    from /home/ricardo/.gem/ruby/1.9.1/gems/thin-1.5.1/lib/rack/adapter/loader.rb:33:in`eval'
    from /home/ricardo/.gem/ruby/1.9.1/gems/thin-1.5.1/lib/rack/adapter/loader.rb:33:in `load'
    from /home/ricardo/.gem/ruby/1.9.1/gems/thin-1.5.1/lib/thin/controllers/controller.rb:181:in`load_rackup_config'
    from /home/ricardo/.gem/ruby/1.9.1/gems/thin-1.5.1/lib/thin/controllers/controller.rb:71:in `start'
    from /home/ricardo/.gem/ruby/1.9.1/gems/thin-1.5.1/lib/thin/runner.rb:187:in`run_command'
    from /home/ricardo/.gem/ruby/1.9.1/gems/thin-1.5.1/lib/thin/runner.rb:152:in `run!'
    from /home/ricardo/.gem/ruby/1.9.1/gems/thin-1.5.1/bin/thin:6:in`<top (required)>'
    from /home/ricardo/bin/thin:23:in `load'
    from /home/ricardo/bin/thin:23:in`<main>'

**[ricardo@iridium sweet_dashboard_project]$ bundle install**
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
Using backports (3.1.1) 
Using coffee-script-source (1.6.2) 
Using multi_json (1.7.2) 
Using execjs (1.4.0) 
Using coffee-script (2.2.0) 
Using daemons (1.1.9) 
Using rack (1.5.2) 
Using tzinfo (0.3.37) 
Using rufus-scheduler (2.0.18) 
Using sass (3.2.7) 
Using rack-protection (1.5.0) 
Using tilt (1.3.6) 
Using sinatra (1.3.6) 
Using eventmachine (1.0.3) 
Using rack-test (0.6.2) 
Using sinatra-contrib (1.3.2) 
Using hike (1.2.1) 
Using sprockets (2.9.0) 
Using thin (1.5.1) 
Using thor (0.18.0) 
Using dashing (1.0.4) 
Using bundler (1.3.4) 
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.

The weird thing is if I run:

[ricardo@iridium sweet_dashboard_project]$ thin start

> > Using rack adapter
> > Thin web server (v1.5.1 codename Straight Razor)
> > Maximum connections set to 1024
> > Listening on 0.0.0.0:3000, CTRL+C to stop

Actually runs the http://127.0.0.1:3000/sample app.

Thanks.

**Comment by shakeelahmed9810** [comment]
i am also facing same issue 

/home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:4:in `require': cannot load such file -- multi_json (LoadError)
	from /home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:4:in `<top (required)>'
	from /home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.8.4/lib/bundler/runtime.rb:76:in `require'
	from /home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.8.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.8.4/lib/bundler/runtime.rb:72:in `each'
	from /home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.8.4/lib/bundler/runtime.rb:72:in `block in require'
	from /home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.8.4/lib/bundler/runtime.rb:61:in `each'
	from /home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.8.4/lib/bundler/runtime.rb:61:in `require'
	from /home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.8.4/lib/bundler.rb:134:in `require'
	from /home/shakeel/rails_projects/test_app/config/application.rb:7:in `<top (required)>'
	from /home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:79:in `require'
	from /home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:79:in `block in server'
	from /home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/shakeel/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'

**Comment by ocontant** [comment]
I'm using dashing on a french CentOS 7 install and have the same issue as described.  This date from 2013 and has been closed without a solution. 

Must I understand this project has been abandoned since then and the book i'm reading is just too old to be pertinent anymore?

**Comment by huaxiaozhong1** [comment]
Hi, I have just fixed the issue on Fedora 22 with rails 5.0.2. After add "gem 'json'" into Gemfile, "rails server" got success. localhost:3000 can be displayed on browser. "cannot load such file -- json (LoadError)" was dissapeared when running "rails server". Thanks!
